// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package recipe

import (
	"database/sql/driver"
	json "encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
)

const (
	// RoastLevelLigth is a RoastLevel of type Ligth.
	RoastLevelLigth RoastLevel = iota
	// RoastLevelMediumLight is a RoastLevel of type Medium_light.
	RoastLevelMediumLight
	// RoastLevelMedium is a RoastLevel of type Medium.
	RoastLevelMedium
	// RoastLevelMediumDark is a RoastLevel of type Medium_dark.
	RoastLevelMediumDark
	// RoastLevelDark is a RoastLevel of type Dark.
	RoastLevelDark
)

var ErrInvalidRoastLevel = fmt.Errorf("not a valid RoastLevel, try [%s]", strings.Join(_RoastLevelNames, ", "))

const _RoastLevelName = "ligthmedium_lightmediummedium_darkdark"

var _RoastLevelNames = []string{
	_RoastLevelName[0:5],
	_RoastLevelName[5:17],
	_RoastLevelName[17:23],
	_RoastLevelName[23:34],
	_RoastLevelName[34:38],
}

// RoastLevelNames returns a list of possible string values of RoastLevel.
func RoastLevelNames() []string {
	tmp := make([]string, len(_RoastLevelNames))
	copy(tmp, _RoastLevelNames)
	return tmp
}

var _RoastLevelMap = map[RoastLevel]string{
	RoastLevelLigth:       _RoastLevelName[0:5],
	RoastLevelMediumLight: _RoastLevelName[5:17],
	RoastLevelMedium:      _RoastLevelName[17:23],
	RoastLevelMediumDark:  _RoastLevelName[23:34],
	RoastLevelDark:        _RoastLevelName[34:38],
}

// String implements the Stringer interface.
func (x RoastLevel) String() string {
	if str, ok := _RoastLevelMap[x]; ok {
		return str
	}
	return fmt.Sprintf("RoastLevel(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RoastLevel) IsValid() bool {
	_, ok := _RoastLevelMap[x]
	return ok
}

var _RoastLevelValue = map[string]RoastLevel{
	_RoastLevelName[0:5]:   RoastLevelLigth,
	_RoastLevelName[5:17]:  RoastLevelMediumLight,
	_RoastLevelName[17:23]: RoastLevelMedium,
	_RoastLevelName[23:34]: RoastLevelMediumDark,
	_RoastLevelName[34:38]: RoastLevelDark,
}

// ParseRoastLevel attempts to convert a string to a RoastLevel.
func ParseRoastLevel(name string) (RoastLevel, error) {
	if x, ok := _RoastLevelValue[name]; ok {
		return x, nil
	}
	return RoastLevel(0), fmt.Errorf("%s is %w", name, ErrInvalidRoastLevel)
}

// MarshalText implements the text marshaller method.
func (x RoastLevel) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RoastLevel) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseRoastLevel(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RoastLevel) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errRoastLevelNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *RoastLevel) Scan(value interface{}) (err error) {
	if value == nil {
		*x = RoastLevel(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = RoastLevel(v)
	case string:
		*x, err = ParseRoastLevel(v)
		if err != nil {
			// try parsing the integer value as a string
			if val, verr := strconv.Atoi(v); verr == nil {
				*x, err = RoastLevel(val), nil
			}
		}
	case []byte:
		*x, err = ParseRoastLevel(string(v))
		if err != nil {
			// try parsing the integer value as a string
			if val, verr := strconv.Atoi(string(v)); verr == nil {
				*x, err = RoastLevel(val), nil
			}
		}
	case RoastLevel:
		*x = v
	case int:
		*x = RoastLevel(v)
	case *RoastLevel:
		if v == nil {
			return errRoastLevelNilPtr
		}
		*x = *v
	case uint:
		*x = RoastLevel(v)
	case uint64:
		*x = RoastLevel(v)
	case *int:
		if v == nil {
			return errRoastLevelNilPtr
		}
		*x = RoastLevel(*v)
	case *int64:
		if v == nil {
			return errRoastLevelNilPtr
		}
		*x = RoastLevel(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = RoastLevel(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errRoastLevelNilPtr
		}
		*x = RoastLevel(*v)
	case *uint:
		if v == nil {
			return errRoastLevelNilPtr
		}
		*x = RoastLevel(*v)
	case *uint64:
		if v == nil {
			return errRoastLevelNilPtr
		}
		*x = RoastLevel(*v)
	case *string:
		if v == nil {
			return errRoastLevelNilPtr
		}
		*x, err = ParseRoastLevel(*v)
		if err != nil {
			// try parsing the integer value as a string
			if val, verr := strconv.Atoi(*v); verr == nil {
				*x, err = RoastLevel(val), nil
			}
		}
	}

	return
}

// Value implements the driver Valuer interface.
func (x RoastLevel) Value() (driver.Value, error) {
	return int64(x), nil
}

type NullRoastLevel struct {
	RoastLevel RoastLevel
	Valid      bool
	Set        bool
}

func NewNullRoastLevel(val interface{}) (x NullRoastLevel) {
	x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	return
}

// Scan implements the Scanner interface.
func (x *NullRoastLevel) Scan(value interface{}) (err error) {
	x.Set = true
	if value == nil {
		x.RoastLevel, x.Valid = RoastLevel(0), false
		return
	}

	err = x.RoastLevel.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullRoastLevel) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	// driver.Value accepts int64 for int values.
	return int64(x.RoastLevel), nil
}

// MarshalJSON correctly serializes a NullRoastLevel to JSON.
func (n NullRoastLevel) MarshalJSON() ([]byte, error) {
	const nullStr = "null"
	if n.Valid {
		return json.Marshal(n.RoastLevel)
	}
	return []byte(nullStr), nil
}

// UnmarshalJSON correctly deserializes a NullRoastLevel from JSON.
func (n *NullRoastLevel) UnmarshalJSON(b []byte) error {
	n.Set = true
	var x interface{}
	err := json.Unmarshal(b, &x)
	if err != nil {
		return err
	}
	err = n.Scan(x)
	return err
}
