### Create a new recipe
POST http://localhost:9090/api/v1/recipes
X-User-Id: test-user
Content-Type: application/json

{
  "title": "Test Recipe",
  "description": "My awesome coffee recipe",
  "brew_method": "v60",
  "difficulty": "easy",
  "roast_level": "medium",
  "beans": "Colombian beans",
  "steps": [
    {"order":1,"title":"Boil water","description":"Heat water to 92C"},
    {"order":2,"title":"Pour over","description":"Pour slowly over coffee grounds"}
  ]
}

### Get your recipes
GET http://localhost:9090/api/v1/recipes
X-User-Id: test-user
Accept: application/json

### Pagination example
GET http://localhost:9090/api/v1/recipes?page=1&limit=1&difficulty=easy
X-User-Id: 123e4567-e89b-12d3-a456-426614174000
Accept: application/json

### Delete your recipe
DELETE http://localhost:9090/api/v1/recipes/c2629d0c-044f-4eca-8911-15fa5d843e71
X-User-Id: 123e4567-e89b-12d3-a456-426614174000
Accept: application/json