// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package models

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for BrewMethod.
const (
	BrewMethodAeropress       BrewMethod = "aeropress"
	BrewMethodChemex          BrewMethod = "chemex"
	BrewMethodColdBrew        BrewMethod = "cold_brew"
	BrewMethodExpressoMachine BrewMethod = "expresso_machine"
	BrewMethodFrenchPress     BrewMethod = "french_press"
	BrewMethodMokaPot         BrewMethod = "moka_pot"
	BrewMethodNone            BrewMethod = "none"
	BrewMethodV60             BrewMethod = "v60"
)

// Valid indicates whether the value is a known member of the BrewMethod enum.
func (e BrewMethod) Valid() bool {
	switch e {
	case BrewMethodAeropress:
		return true
	case BrewMethodChemex:
		return true
	case BrewMethodColdBrew:
		return true
	case BrewMethodExpressoMachine:
		return true
	case BrewMethodFrenchPress:
		return true
	case BrewMethodMokaPot:
		return true
	case BrewMethodNone:
		return true
	case BrewMethodV60:
		return true
	default:
		return false
	}
}

// Defines values for Difficulty.
const (
	DifficultyEasy   Difficulty = "easy"
	DifficultyHard   Difficulty = "hard"
	DifficultyMedium Difficulty = "medium"
	DifficultyNone   Difficulty = "none"
)

// Valid indicates whether the value is a known member of the Difficulty enum.
func (e Difficulty) Valid() bool {
	switch e {
	case DifficultyEasy:
		return true
	case DifficultyHard:
		return true
	case DifficultyMedium:
		return true
	case DifficultyNone:
		return true
	default:
		return false
	}
}

// Defines values for RoastLevel.
const (
	Dark        RoastLevel = "dark"
	Ligth       RoastLevel = "ligth"
	Medium      RoastLevel = "medium"
	MediumDark  RoastLevel = "medium_dark"
	MediumLight RoastLevel = "medium_light"
	None        RoastLevel = "none"
)

// Valid indicates whether the value is a known member of the RoastLevel enum.
func (e RoastLevel) Valid() bool {
	switch e {
	case Dark:
		return true
	case Ligth:
		return true
	case Medium:
		return true
	case MediumDark:
		return true
	case MediumLight:
		return true
	case None:
		return true
	default:
		return false
	}
}

// BrewMethod Coffee brewing method
type BrewMethod string

// Difficulty Difficulty level of the recipe
type Difficulty string

// RoastLevel Coffee roast level
type RoastLevel string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/2yRz2rjMBCHX8XMWRgvC3vQcdtjc+m1BKPYI0tE0ghpnD8Ev3uZuGkLzsljz/j3fSPd",
	"YKCYKWHiCvoGdXAYzb38X/C8Q3Y0ytuIdSg+s6cEGl7IWsTmUPDs09TEdUwBpjmC/oBECUHB6V8HCmzB",
	"NLg+F6wVFBgs9KiFhhcpKIy9xEnI5d6mPprB+XtQpKPpMzHsFfA1I2ioXHyaYFHw6q31wxz4uhX96TUB",
	"Txgasg07bAoOPuPWGE29Cg9HP0dQ4EwZn0LfyVR+k8gVas0cGPQj5+lxFfln9diSg5/YfaP74CfHv02+",
	"vo+mHCVfHnsFaQ7BHAKC5jLjxnNZFPhkSRzZs8zBjkYMtaEUZNMTlrpKdm3X/pHVKGMy2YOGv23Xyg1m",
	"w66CFtjyGQAA//95HVwCMgIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
