// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package models

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BrewMethod.
const (
	Aeropress       BrewMethod = "aeropress"
	Chemex          BrewMethod = "chemex"
	ColdBrew        BrewMethod = "cold_brew"
	ExpressoMachine BrewMethod = "expresso_machine"
	FrenchPress     BrewMethod = "french_press"
	MokaPot         BrewMethod = "moka_pot"
	V60             BrewMethod = "v60"
)

// Valid indicates whether the value is a known member of the BrewMethod enum.
func (e BrewMethod) Valid() bool {
	switch e {
	case Aeropress:
		return true
	case Chemex:
		return true
	case ColdBrew:
		return true
	case ExpressoMachine:
		return true
	case FrenchPress:
		return true
	case MokaPot:
		return true
	case V60:
		return true
	default:
		return false
	}
}

// Defines values for Difficulty.
const (
	DifficultyEasy   Difficulty = "easy"
	DifficultyHard   Difficulty = "hard"
	DifficultyMedium Difficulty = "medium"
)

// Valid indicates whether the value is a known member of the Difficulty enum.
func (e Difficulty) Valid() bool {
	switch e {
	case DifficultyEasy:
		return true
	case DifficultyHard:
		return true
	case DifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for LikeTargetType.
const (
	LikeTargetTypeRecipe LikeTargetType = "recipe"
)

// Valid indicates whether the value is a known member of the LikeTargetType enum.
func (e LikeTargetType) Valid() bool {
	switch e {
	case LikeTargetTypeRecipe:
		return true
	default:
		return false
	}
}

// Defines values for RoastLevel.
const (
	RoastLevelDark        RoastLevel = "dark"
	RoastLevelLight       RoastLevel = "light"
	RoastLevelMedium      RoastLevel = "medium"
	RoastLevelMediumDark  RoastLevel = "medium_dark"
	RoastLevelMediumLight RoastLevel = "medium_light"
)

// Valid indicates whether the value is a known member of the RoastLevel enum.
func (e RoastLevel) Valid() bool {
	switch e {
	case RoastLevelDark:
		return true
	case RoastLevelLight:
		return true
	case RoastLevelMedium:
		return true
	case RoastLevelMediumDark:
		return true
	case RoastLevelMediumLight:
		return true
	default:
		return false
	}
}

// ApiErrorResponse defines model for ApiErrorResponse.
type ApiErrorResponse struct {
	// Error Human-readable error message
	Error string `json:"error"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken Short-lived token for authenticating requests
	AccessToken string `json:"access_token"`

	// RefreshToken Token used to obtain a new access token
	RefreshToken string       `json:"refresh_token"`
	User         UserResponse `json:"user"`
}

// BrewMethod Coffee brewing method
type BrewMethod string

// BrewStep Single step of the brewing process
type BrewStep struct {
	// Description Detailed instructions for the step
	Description *string `json:"description,omitempty"`

	// DurationSeconds Optional duration of the step in seconds
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// Id Unique step identifier
	Id int64 `json:"id"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// Order Order of the step in the recipe
	Order int `json:"order"`

	// Title Short title of the step
	Title string `json:"title"`
}

// BrewStepPayload Single step of the brewing process
type BrewStepPayload struct {
	// Description Detailed instructions for the step
	Description *string `json:"description,omitempty"`

	// DurationSeconds Optional duration of the step in seconds
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// Order Order of the step in the recipe
	Order int `json:"order"`

	// Title Short title of the step
	Title string `json:"title"`
}

// CreateRecipeRequest defines model for CreateRecipeRequest.
type CreateRecipeRequest = RecipePayload

// Difficulty Difficulty level of the recipe
type Difficulty string

// Image Uploaded image
type Image struct {
	// Id Unique image identifier
	Id string `json:"id"`
}

// LikeTargetType Type of the liked object
type LikeTargetType string

// LimitParam Number of items per page
type LimitParam = int32

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password User password
	Password string `json:"password"`

	// Username Unique username
	Username string `json:"username"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// MyProfile defines model for MyProfile.
type MyProfile = UserResponse

// Page Generic paginated response
type Page struct {
	// Items List of items on this page
	Items      []interface{}  `json:"items"`
	Pagination PaginationMeta `json:"pagination"`
}

// PageParam Page number
type PageParam = int32

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// CurrentPage Current page number
	CurrentPage int32 `json:"current_page"`

	// ItemsCount Number of items on the current page
	ItemsCount int32 `json:"items_count"`

	// LastPage Last page number
	LastPage int32 `json:"last_page"`

	// NextPage Next page number
	NextPage int32 `json:"next_page"`
}

// PaginationParams defines model for PaginationParams.
type PaginationParams struct {
	// Limit Number of items per page
	Limit *LimitParam `json:"limit,omitempty"`

	// Page Page number
	Page *PageParam `json:"page,omitempty"`
}

// Recipe Coffee brewing recipe
type Recipe struct {
	// AuthorId ID of the user who created the recipe
	AuthorId string `json:"author_id"`

	// Beans Coffee beans used for the recipe
	Beans *string `json:"beans,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod BrewMethod `json:"brew_method"`

	// CreatedAt Timestamp when the recipe was created
	CreatedAt time.Time `json:"created_at"`

	// Description Detailed description of the recipe
	Description string `json:"description"`

	// Difficulty Difficulty level of the recipe
	Difficulty Difficulty `json:"difficulty"`

	// Id Unique recipe identifier
	Id string `json:"id"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// IsLiked Whether the current user has liked this recipe
	IsLiked bool `json:"is_liked"`

	// LikesCount Total number of likes
	LikesCount int32 `json:"likes_count"`

	// Public Indicates whether the recipe is publicly visible.
	Public bool `json:"public"`

	// RoastLevel Coffee roast level
	RoastLevel *RoastLevel `json:"roast_level,omitempty"`

	// Steps Ordered list of brewing steps
	Steps []BrewStep `json:"steps"`

	// Title Recipe title
	Title string `json:"title"`

	// UpdatedAt Timestamp when the recipe was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// RecipePayload defines model for RecipePayload.
type RecipePayload struct {
	// Beans Coffee beans used for the recipe
	Beans *string `json:"beans,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod BrewMethod `json:"brew_method"`

	// Description Detailed description of the recipe
	Description string `json:"description"`

	// Difficulty Difficulty level of the recipe
	Difficulty Difficulty `json:"difficulty"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// Public Indicates whether the recipe is publicly visible
	Public *bool `json:"public,omitempty"`

	// RoastLevel Coffee roast level
	RoastLevel *RoastLevel `json:"roast_level,omitempty"`

	// Steps Ordered list of brewing steps
	Steps []BrewStepPayload `json:"steps"`

	// Title Recipe title
	Title string `json:"title"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Refresh token obtained during login or registration
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// AvatarId ID of the uploaded avatar image. Can be resolved via the image upload endpoint.
	AvatarId *string `json:"avatar_id,omitempty"`

	// Bio Short user biography
	Bio *string `json:"bio,omitempty"`

	// Email User email address
	Email openapi_types.Email `json:"email"`

	// Password User password. Must be 8-32 characters.
	Password string `json:"password"`

	// Username Unique username. Must be 6-16 characters, letters, numbers and underscores only.
	Username string `json:"username"`
}

// RoastLevel Coffee roast level
type RoastLevel string

// ToggleLikeResponse defines model for ToggleLikeResponse.
type ToggleLikeResponse struct {
	// Liked True if like was added, false if removed
	Liked bool `json:"liked"`

	// LikesCount Updated total likes count
	LikesCount int32 `json:"likes_count"`
}

// TokensResponse defines model for TokensResponse.
type TokensResponse struct {
	// AccessToken Short-lived token for authenticating requests
	AccessToken string `json:"access_token"`

	// RefreshToken Token used to obtain a new access token
	RefreshToken string `json:"refresh_token"`
}

// UpdateRecipeRequest defines model for UpdateRecipeRequest.
type UpdateRecipeRequest = RecipePayload

// UserProfile defines model for UserProfile.
type UserProfile struct {
	// AvatarId ID of the uploaded avatar image. Can be resolved via the image upload endpoint.
	AvatarId *string `json:"avatar_id,omitempty"`

	// Bio Short user biography
	Bio *string `json:"bio,omitempty"`

	// Id Unique user identifier
	Id string `json:"id"`

	// Username Unique username
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// AvatarId ID of the uploaded avatar image. Can be resolved via the image upload endpoint.
	AvatarId *string `json:"avatar_id,omitempty"`

	// Bio Short user biography
	Bio *string `json:"bio,omitempty"`

	// Id Unique user identifier
	Id string `json:"id"`

	// Username Unique username
	Username string `json:"username"`
}

// ListRecipesParams defines model for ListRecipesParams.
type ListRecipesParams struct {
	// AuthorId Filter by author
	AuthorId *string `json:"authorId,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod *BrewMethod `json:"brewMethod,omitempty"`

	// Difficulty Difficulty level of the recipe
	Difficulty *Difficulty `json:"difficulty,omitempty"`

	// Limit Number of items per page
	Limit *LimitParam `json:"limit,omitempty"`

	// Page Page number
	Page *PageParam `json:"page,omitempty"`

	// SortDirection Sort direction
	SortDirection *string `json:"sort_direction,omitempty"`

	// SortField Field to sort by, e.g. created_at, title, difficulty
	SortField *string `json:"sort_field,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX2/bOBL/KgTvHhU3aQ/FwW+77f0p4GyDbIp7WBQGLY4kXihSJakkRpDvfhhSsiSL",
	"slz3Fsjd+imKNBrODH8z/M3IzzTVZaUVKGfp8plWzLASHBj/30pYdwupqMDe4AN/E54qqTnQpTM1JFQo",
	"uqTfajBbmlDFSqBLKrv3aEJtWkDJ8FUm5eeMLn97pn82kNEl/dObbvk3Qc6+uWG5UMwJrZpFX5JnWhld",
	"gXECvA2sdoU2nzhec7CpERXK0yX9u5AODNlsSZChCXXbCo2yzgiV05eEbgw8XoMrtH//kCk/d5IvCeUi",
	"y0RaS7ede+9jJ/mSUKuNW3NhIA1G7tv8qzaOdM8TCqou6fI3ymxKEy9Mv0b88HozATIaB5CcOE1QiGy2",
	"CYFFviCpAeaAr5lLiBNOQkJ6XnUrd3IYQBSMWPCyu6M3/4bU0ZevaJXbSryXaVN6mSYoaONPlfibMdrc",
	"gq20suAhN9hZwMdjd/5Zl0xdGGCcbSQQL0VKsJblQGOGGfhWCwMcnQk6v46sTehPtSumbWFpCtaunb6H",
	"2K4V2rgLKR4A43wPimTaeNSBciJlTqicoBlgnY3B0EBmwBZT+u+8ztp69URvHBOKMKLgkQTDwqoxzbUF",
	"MwfRLxa6bdiP2NC0ZBiJRn8snj8PMmvozwedZQAEkw8jUwaxDnIP7y9pQjMDKi3WlQGLQWNgdHuNhsMT",
	"XmjJ16gH337yj/W6ZGkhFIKh1PdsXWkXzRm08FcHVWQ/hcolEOugIjojruhsrYxOgw1DgAwU7Ov7CI4J",
	"CZwIZZ2pfW5bjxFUjcvEto7Xxpe+tYVUKz5ehn72F0ySVrS11lsuFGnfTKiqpcR8aWt1s5pQDnIwuJyI",
	"bNQXJb7VrTqOYM4EYCHFjGYuKHj/FxrVV7Ic1jGtnz62dtaV1IxjYFB4QT4wRTZADFgtMZkeBPNy/nEj",
	"TUDxSgvlFtNudUHUhkOkiHzG2/vRwmvjz6qoQ6H2xZM/VNC+wtlSJBDxwbxxXR3mEaL0hm3Re1+MOBdh",
	"4296GMyYtJCckXxG3hzy5kH3wZ/5gbfdhnNrFnhDFG2AKTtd+fFpONBa7Ozcnw0sAnhdnkLajkJ273Yb",
	"1f2t6SH7RB74OiBa1Rsp0mBDxmrpJqrIJ8WRxYAljwW4Avo7RoQlQY/ckgdhBS64W2ujtQSmPMfRzLq1",
	"hAeQc7G6RdGVl/QsEio7kUjACXYYGLK2rgXxhAoHoUuZA0i/unY8lhnDtgeSLyRHyL7ZjGul+iqGQB5A",
	"qfU5lpofB4jbw/DuGfFxHuG3JVjALK5SAhd1SRNaMMOjHOkTYivCCwbQHB0hB6hEAOuAS8wek7EwrMQ9",
	"3DGTg7vzj0aUeVvtiqIU98BJ824XhCYqMbdXohTOt5yD5Hh7uZ8Zv9TlJpRzDzdSgSFVCEmfIr17G63r",
	"K50LdVp9rZi1j9rEAm29Dc3jnh29e6VQK1C5K+jyaqJpCP37xC7uBGZU7e1lz4Kdhujm6lzXrheYoe+j",
	"bunwqkPx2HrX2xujMxHS/LjJxLBnwmb3Jpop/wAFRqQICqGwj8b6Hd4aZU1bsIYaVk19CwDTSBaw5AaQ",
	"te9E6la1m53MFcFuynINjo0z0K8xUBgLIvo/Tpmr/YxBMaJ82sSSpBRKlJifV7GE2bN0hIy0NgaUW1fR",
	"vfgQnvrYnWyCj8Y61bVy4xX2y4EO1C7tLXxwxcvYihLPzbhHK2Z/0B0FT1PKf4GnH1Ieg1ETuGS4U30z",
	"+v5OwGw4EhyBQGLxnsN8r8KHXIEjsqTBd2TalTR8YHbWsTuKY1PMOUKIlf2x0O3oboabvkYK3hsmjo9s",
	"UYJ1rKyQZfZ7IvLIbOtzH4ScObhwoowz81dE9qfpUMuhD/Ch19IsCLv2RGpsxb96TUFb6jxWC2Yb8uXP",
	"rP3I9poDlJqsqnfaMdkUIfTXCx/HsPodzo90NIv/vZbmv9bLJLSu+IlZi7WcNK8fmbqxMVlXHpNTe6kd",
	"FpLhF42eb0MY9hD/dbLeHzuVOw9HzsOR83Dkdx+O3IZW77SWeuYjXKO7+cAXPsJhRtToFJHYyhNtiIFc",
	"WBeG2LOuz7emt14d9pqnuMQemGPm2FQK0r9fRm2Enhpie7qwETo3rCq2xyiDkgk5Mf3wzwjjvPlcuDt2",
	"wkuxZD9unLIg17V1GJa/Xrx7S9KCGZY6MHYxMWg5fbTSLfX+4up9b6mESHDhIlAiS5jipFYcjE21AWw7",
	"5XYx/y28CcaxU5le4Zk6unwZC7PH3qBNirxwu3Hjevhvd58zc4+pjn9iQ7k7necSVuIe+t/pvyMbJujr",
	"namBiEArPWlhnANPiNeBDwyU+gH49xPXL4FbEOcJrBclLbmYJa97uxWMHy4Y2yX/WwH7f/dLhr1o7P0K",
	"Yb6Ohq04f9E6k7YzaXtlpA1P2N78/Q/DYA6Mhbyyw0Oh7/lGc0SHffDkH3zsOG/R69silBcq85432U2v",
	"NQcZuCBN6AMYG9a+XFwurvwPVCpQrBJ0Sd8tLheXngm6wtIlhuXlPwEAAP//pmM8Hg8sAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
