// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package models

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BrewMethod.
const (
	Aeropress       BrewMethod = "aeropress"
	Chemex          BrewMethod = "chemex"
	ColdBrew        BrewMethod = "cold_brew"
	ExpressoMachine BrewMethod = "expresso_machine"
	FrenchPress     BrewMethod = "french_press"
	MokaPot         BrewMethod = "moka_pot"
	V60             BrewMethod = "v60"
)

// Valid indicates whether the value is a known member of the BrewMethod enum.
func (e BrewMethod) Valid() bool {
	switch e {
	case Aeropress:
		return true
	case Chemex:
		return true
	case ColdBrew:
		return true
	case ExpressoMachine:
		return true
	case FrenchPress:
		return true
	case MokaPot:
		return true
	case V60:
		return true
	default:
		return false
	}
}

// Defines values for Difficulty.
const (
	DifficultyEasy   Difficulty = "easy"
	DifficultyHard   Difficulty = "hard"
	DifficultyMedium Difficulty = "medium"
)

// Valid indicates whether the value is a known member of the Difficulty enum.
func (e Difficulty) Valid() bool {
	switch e {
	case DifficultyEasy:
		return true
	case DifficultyHard:
		return true
	case DifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for RoastLevel.
const (
	RoastLevelDark        RoastLevel = "dark"
	RoastLevelLight       RoastLevel = "light"
	RoastLevelMedium      RoastLevel = "medium"
	RoastLevelMediumDark  RoastLevel = "medium_dark"
	RoastLevelMediumLight RoastLevel = "medium_light"
)

// Valid indicates whether the value is a known member of the RoastLevel enum.
func (e RoastLevel) Valid() bool {
	switch e {
	case RoastLevelDark:
		return true
	case RoastLevelLight:
		return true
	case RoastLevelMedium:
		return true
	case RoastLevelMediumDark:
		return true
	case RoastLevelMediumLight:
		return true
	default:
		return false
	}
}

// ApiErrorResponse defines model for ApiErrorResponse.
type ApiErrorResponse struct {
	// Error Human-readable error message
	Error string `json:"error"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken Short-lived token for authenticating requests
	AccessToken string `json:"access_token"`

	// RefreshToken Token used to obtain a new access token
	RefreshToken string       `json:"refresh_token"`
	User         UserResponse `json:"user"`
}

// BrewMethod Coffee brewing method
type BrewMethod string

// BrewStep Single step of the brewing process
type BrewStep struct {
	// Description Detailed instructions for the step
	Description string `json:"description"`

	// DurationSeconds Optional duration of the step in seconds
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// Id Unique step identifier
	Id int64 `json:"id"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// Order Order of the step in the recipe
	Order int `json:"order"`

	// Title Short title of the step
	Title string `json:"title"`
}

// BrewStepPayload Single step of the brewing process
type BrewStepPayload struct {
	// Description Detailed instructions for the step
	Description string `json:"description"`

	// DurationSeconds Optional duration of the step in seconds
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// Order Order of the step in the recipe
	Order int `json:"order"`

	// Title Short title of the step
	Title string `json:"title"`
}

// CreateRecipeRequest defines model for CreateRecipeRequest.
type CreateRecipeRequest = RecipePayload

// Difficulty Difficulty level of the recipe
type Difficulty string

// Image Uploaded image
type Image struct {
	// Id Unique image identifier
	Id string `json:"id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password User password
	Password string `json:"password"`

	// Username Unique username
	Username string `json:"username"`
}

// MyProfile defines model for MyProfile.
type MyProfile = UserResponse

// Page Generic paginated response
type Page struct {
	// Items List of items on this page
	Items      []interface{}  `json:"items"`
	Pagination PaginationMeta `json:"pagination"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// CurrentPage Current page number
	CurrentPage int32 `json:"current_page"`

	// ItemsCount Number of items on the current page
	ItemsCount int32 `json:"items_count"`

	// LastPage Last page number
	LastPage int32 `json:"last_page"`

	// NextPage Next page number
	NextPage int32 `json:"next_page"`
}

// PaginationParams defines model for PaginationParams.
type PaginationParams struct {
	// Limit Number of items per page
	Limit *int32 `json:"limit,omitempty"`

	// Page Page number
	Page *int32 `json:"page,omitempty"`
}

// PatchRecipeRequest defines model for PatchRecipeRequest.
type PatchRecipeRequest struct {
	Beans *string `json:"beans,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod  *BrewMethod `json:"brew_method,omitempty"`
	Description *string     `json:"description,omitempty"`

	// Difficulty Difficulty level of the recipe
	Difficulty *Difficulty `json:"difficulty,omitempty"`
	ImageId    *string     `json:"image_id,omitempty"`

	// Public Whether this recipe is publicly visible
	Public *bool `json:"public,omitempty"`

	// RoastLevel Coffee roast level
	RoastLevel *RoastLevel `json:"roast_level,omitempty"`
	Title      *string     `json:"title,omitempty"`
}

// Recipe Coffee brewing recipe
type Recipe struct {
	// AuthorId ID of the user who created the recipe
	AuthorId string `json:"author_id"`

	// Beans Coffee beans used for the recipe
	Beans *string `json:"beans,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod BrewMethod `json:"brew_method"`

	// CreatedAt Timestamp when the recipe was created
	CreatedAt time.Time `json:"created_at"`

	// Description Detailed description of the recipe
	Description string `json:"description"`

	// Difficulty Difficulty level of the recipe
	Difficulty Difficulty `json:"difficulty"`

	// Id Unique recipe identifier
	Id string `json:"id"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// Public Indicates whether the recipe is publicly visible.
	Public bool `json:"public"`

	// RoastLevel Coffee roast level
	RoastLevel *RoastLevel `json:"roast_level,omitempty"`

	// Steps Ordered list of brewing steps
	Steps []BrewStep `json:"steps"`

	// Title Recipe title
	Title string `json:"title"`

	// UpdatedAt Timestamp when the recipe was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// RecipePayload defines model for RecipePayload.
type RecipePayload struct {
	// Beans Coffee beans used for the recipe
	Beans *string `json:"beans,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod BrewMethod `json:"brew_method"`

	// Description Detailed description of the recipe
	Description string `json:"description"`

	// Difficulty Difficulty level of the recipe
	Difficulty Difficulty `json:"difficulty"`

	// ImageId ID of the uploaded image. Can be resolved via the image upload endpoint.
	ImageId *string `json:"image_id,omitempty"`

	// Public Indicates whether the recipe is publicly visible
	Public *bool `json:"public,omitempty"`

	// RoastLevel Coffee roast level
	RoastLevel *RoastLevel `json:"roast_level,omitempty"`

	// Steps Ordered list of brewing steps
	Steps []BrewStepPayload `json:"steps"`

	// Title Recipe title
	Title string `json:"title"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Refresh token obtained during login or registration
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// AvatarId ID of the uploaded avatar image. Can be resolved via the image upload endpoint.
	AvatarId *string `json:"avatar_id,omitempty"`

	// Bio Short user biography
	Bio *string `json:"bio,omitempty"`

	// Email User email address
	Email openapi_types.Email `json:"email"`

	// Password User password. Must be 8-32 characters.
	Password string `json:"password"`

	// Username Unique username. Must be 6-16 characters, letters, numbers and underscores only.
	Username string `json:"username"`
}

// RoastLevel Coffee roast level
type RoastLevel string

// TokensResponse defines model for TokensResponse.
type TokensResponse struct {
	// AccessToken Short-lived token for authenticating requests
	AccessToken string `json:"access_token"`

	// RefreshToken Token used to obtain a new access token
	RefreshToken string `json:"refresh_token"`
}

// UpdateRecipeRequest defines model for UpdateRecipeRequest.
type UpdateRecipeRequest = RecipePayload

// UserProfile defines model for UserProfile.
type UserProfile struct {
	// AvatarId ID of the uploaded avatar image. Can be resolved via the image upload endpoint.
	AvatarId *string `json:"avatar_id,omitempty"`

	// Bio Short user biography
	Bio *string `json:"bio,omitempty"`

	// Id Unique user identifier
	Id string `json:"id"`

	// Username Unique username
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// AvatarId ID of the uploaded avatar image. Can be resolved via the image upload endpoint.
	AvatarId *string `json:"avatar_id,omitempty"`

	// Bio Short user biography
	Bio *string `json:"bio,omitempty"`

	// Id Unique user identifier
	Id string `json:"id"`

	// Username Unique username
	Username string `json:"username"`
}

// ListRecipesParams defines model for ListRecipesParams.
type ListRecipesParams struct {
	// AuthorId Filter by author
	AuthorId *string `json:"authorId,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod *BrewMethod `json:"brewMethod,omitempty"`

	// Difficulty Difficulty level of the recipe
	Difficulty *Difficulty `json:"difficulty,omitempty"`

	// Limit Number of items per page
	Limit *int32 `json:"limit,omitempty"`

	// Page Page number
	Page *int32 `json:"page,omitempty"`

	// SortDirection Sort direction
	SortDirection *string `json:"sort_direction,omitempty"`

	// SortField Field to sort by, e.g. created_at, title, difficulty
	SortField *string `json:"sort_field,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W7bOhJ+FYK7l4rrtItg4btzkv0JkLRBusVeFIFBiyOLG4pUSSqJEeTdF0NKlmRT",
	"luu0RXaPr+qIw/njN8OZYZ9pqotSK1DO0tkzLZlhBTgw/q8rYd0tpKIEe4ML/iM8lVJzoDNnKkioUHRG",
	"v1VgVjShihVAZ1S2+2hCbZpDwXArk/JTRmdfn+mfDWR0Rv/0rhX/LtDZdzdsKRRzQqta6EvyTEujSzBO",
	"gNeBVS7X5pLjbw42NaJEejqjfxfSgSGLFQk0NKFuVaJS1hmhlvQloQsDj9fgcu3371Ll95byJaFcZJlI",
	"K+lWY/suWsqXhFpt3JwLA2lQclPnz9o40q4nFFRV0NlXymxKE09M7yJ2eL6ZABn1A0hOnCZIRBarhMBk",
	"OSGpAeaAz5lLiBNOQkI6VrWSWzp0IBJGNHhZf9GL/0Dq6MsdauVWEr9l2hSepnYK6vhbKf5mjDa3YEut",
	"LHjI9U4WcHnbnH9WBVMnBhhnCwnEU5ECrGVLoDHFDHyrhAGOxgSed1vaJvS3yuXDurA0BWvnTt9D7NRy",
	"bdyJFA+Afr4HRTJtPOpAOZEyJ9SSoBpgnY3B0EBmwOZD/P/leVbWsyd64ZhQhBEFjyQoFqTGOFcWzBhE",
	"v1hoj2HTY33Vkr4nav4xf/7ei6y+Pec6ywAIBh96pghkLeQezqY0oZkBlebz0oBFpzEwuvmNisMT/tCS",
	"z5EP7n7yy3pesDQXCsFQ6Hs2L7WLxgxq+NlBGTlPoZYSiHVQEp0Rl7e6lkanQYc+QHoMNvldgGNCAidC",
	"WWcqH9vWYwRZo5jY0fHK+NQ3t5BqxbfF0E/+B5OkIW209ZoLRZqdCVWVlBgvTa6upQnlYAkGxYnIQX1R",
	"4lvVsOMI5kwAJlKMaOYCg7O/0Ci/gi1hHuN6edHoWZVSM46OQeIJOWeKLIAYsFpiMD0I5un8ck1NQPFS",
	"C+Umw2a1TtSGQySJfMLPm97C38bfVVGDQu6LB3/IoF2Go6lIIOKDeg3vpMd6KKoQszdshb7wqYlzEWBw",
	"00FkxqSF5IjrIw7HcPi9EDz39UCo6W7DnTYKwz6mFsCUHb4VcDVcdg2S1s4YdTPCeV4cUtDthfPO58bH",
	"mwfVwfmBNeLbAGxZLaRIgw4Zq6QbyCmXimOFA5Y85uBy6J4YEZYEPnJFHoQVC9nx1EJrCUz5+kcz6+YS",
	"HkCO+eoWSa88pa8wobQDYQWcYPeBLmuyXCBPqHAQOpgxgHRzbVvjMmPYakcohuAgTUTtjr9Y3PWB3INS",
	"Y3MsNC96iNvA8HqNeD9v4bcpvoBZlFIAF1VBE5ozw6P10yViK1Iz9KC5daHsKDMCWHt1xugVGnPDlV4K",
	"dVhqKpm1j9rEdLRgyHq5UwF1vhVCXYFaupzOTgdq8dAWDzhgTTDCasMNHQ3WHGJ+uV7dGJ2JgNj9GvB+",
	"a4A93U300P8BCoxISRkaduCYisKuLQA0sdfncFWHql8mGm9BzB4BQs2eSAiW6xHBWDy3w4RrcGwbTF5G",
	"j2HMiRtctjrFtDIGlJuXUT+dh1VvF1FVsdiqpj+8D6cvCgzH02hFg5rOU10pty3ho2e64UkgaUfwTonT",
	"mESJ6Tlu0RWzrzRHwdMQ84/w9CrmsSOuHZf0T6qrRtfe3RBoR2F9EEhRCNe7O99Pk5GDKn1+GTgd9lTb",
	"OJ2OubP1ZC36dFPyzascGnGHS/MfUg/+svLup9Rq31VSdc/j3+vCSdhfVjmtS5fRSV5S1zOjc5x1KRGb",
	"0I4VtHi9Pua6GUuO1NZvsYXoDEq3J3iiAOtYUWKV3O3wyCOzjc3dYOTMwYkTRbyzeEPNynA51yB5Rz33",
	"Fpud1zQ3k/+97uaHtTUJrUp+YADgfUvq7XtGQWya1maa5NC2ao2FpP/w0bHtbjBD7juVO45DjuOQ4zjk",
	"p49DbsPT1WFF6ciTXM27fu4LT3IYERUaRaReCkW0IQaWwrowxB41vS8ybhGyw5b8EJPYA3PM7BtKgfrn",
	"RdRC6KEhti8GF0IvDSvz1T7MoGBCDgxt/BphnNePh+vbJWyKBft+U6AJua6sQ7f89eTDe5LmzLDUgbGT",
	"gfnQ4ROhVtTZyelZR1RCJLjwI3R0ljDFSaU4GJtqA5ZoJVeT8Zfx2hn7DpM6iWfo6vJpLEwbO/NFKZa5",
	"Ww8Y5/0/2++cmXsMdfwnNn30b+L2/+7FfuNUNl7bxzPEF1+nHF9njuXIsRx5Y+UI3h2dAfwf5m7eMSLw",
	"zHYPCL7n0WSPFnHnndZ77Tge0ds7IqQXKvOW19FNrzUHGaocmtAHMDbInk6mk1P/Xy9KUKwUdEY/TKaT",
	"qa9xXG7pDN3y8t8AAAD//4qSlhP3KgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
