//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/nikpivkin/roasti-app-backend/internal/api/models"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// CreateRecipeRequest defines model for CreateRecipeRequest.
type CreateRecipeRequest struct {
	Beans *string `json:"beans,omitempty"`

	// BrewMethod Coffee brewing method
	BrewMethod  externalRef0.BrewMethod `json:"brew_method"`
	Description string                  `json:"description"`

	// Difficulty Difficulty level of the recipe
	Difficulty externalRef0.Difficulty `json:"difficulty"`

	// ImageUrl Optional image illustrating the recipe
	ImageUrl *string `json:"image_url,omitempty"`
	Public   *bool   `json:"public,omitempty"`

	// RoastLevel Coffee roast level
	RoastLevel *externalRef0.RoastLevel `json:"roast_level,omitempty"`
	Steps      []externalRef0.BrewStep  `json:"steps"`
	Title      string                   `json:"title"`
}

// CreateRecipeResponse Coffee brewing recipe
type CreateRecipeResponse = externalRef0.Recipe

// PaginatedRecipes defines model for PaginatedRecipes.
type PaginatedRecipes struct {
	Items []externalRef0.Recipe `json:"items"`

	// Limit Maximum number of items per page
	Limit uint64 `json:"limit"`

	// Page Current page number
	Page uint64 `json:"page"`

	// TotalCount Total number of items available
	TotalCount int64 `json:"total_count"`
}

// PaginatedResult Generic paginated response
type PaginatedResult struct {
	// Items List of items on this page
	Items []interface{} `json:"items"`

	// Limit Maximum number of items per page
	Limit uint64 `json:"limit"`

	// Page Current page number
	Page uint64 `json:"page"`

	// TotalCount Total number of items available
	TotalCount int64 `json:"total_count"`
}

// AuthorIDParam defines model for AuthorIDParam.
type AuthorIDParam = string

// BrewMethodParam Coffee brewing method
type BrewMethodParam = externalRef0.BrewMethod

// DifficultyParam Difficulty level of the recipe
type DifficultyParam = externalRef0.Difficulty

// LimitParam defines model for LimitParam.
type LimitParam = int

// PageParam defines model for PageParam.
type PageParam = int

// UserIDHeader defines model for UserIDHeader.
type UserIDHeader = string

// GetApiV1RecipesParams defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParams struct {
	// AuthorId ID of the author
	AuthorId *AuthorIDParam `form:"author_id,omitempty" json:"author_id,omitempty"`

	// BrewMethod Filter by brew method
	BrewMethod *BrewMethodParam `form:"brew_method,omitempty" json:"brew_method,omitempty"`

	// Difficulty Filter by difficulty
	Difficulty *DifficultyParam `form:"difficulty,omitempty" json:"difficulty,omitempty"`

	// Limit Maximum number of recipes to return
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page of recipes
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// XUserId User ID
	XUserId UserIDHeader `json:"X-User-Id"`
}

// PostApiV1RecipesParams defines parameters for PostApiV1Recipes.
type PostApiV1RecipesParams struct {
	// XUserId User ID
	XUserId UserIDHeader `json:"X-User-Id"`
}

// DeleteApiV1RecipesRecipeIdParams defines parameters for DeleteApiV1RecipesRecipeId.
type DeleteApiV1RecipesRecipeIdParams struct {
	// XUserId User ID
	XUserId UserIDHeader `json:"X-User-Id"`
}

// PostApiV1RecipesJSONRequestBody defines body for PostApiV1Recipes for application/json ContentType.
type PostApiV1RecipesJSONRequestBody = CreateRecipeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List recipes
	// (GET /api/v1/recipes)
	GetApiV1Recipes(w http.ResponseWriter, r *http.Request, params GetApiV1RecipesParams)
	// Create recipe
	// (POST /api/v1/recipes)
	PostApiV1Recipes(w http.ResponseWriter, r *http.Request, params PostApiV1RecipesParams)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string, params DeleteApiV1RecipesRecipeIdParams)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1Recipes operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Recipes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1RecipesParams

	// ------------- Optional query parameter "author_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "author_id", r.URL.Query(), &params.AuthorId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author_id", Err: err})
		return
	}

	// ------------- Optional query parameter "brew_method" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "brew_method", r.URL.Query(), &params.BrewMethod, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "brew_method", Err: err})
		return
	}

	// ------------- Optional query parameter "difficulty" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "difficulty", r.URL.Query(), &params.Difficulty, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "difficulty", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Recipes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Recipes operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Recipes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiV1RecipesParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Recipes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1RecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiV1RecipesRecipeIdParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1RecipesRecipeId(w, r, recipeId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes", wrapper.GetApiV1Recipes)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/recipes", wrapper.PostApiV1Recipes)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.DeleteApiV1RecipesRecipeId)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}

type GetApiV1RecipesRequestObject struct {
	Params GetApiV1RecipesParams
}

type GetApiV1RecipesResponseObject interface {
	VisitGetApiV1RecipesResponse(w http.ResponseWriter) error
}

type GetApiV1Recipes200JSONResponse PaginatedRecipes

func (response GetApiV1Recipes200JSONResponse) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Recipes400Response struct {
}

func (response GetApiV1Recipes400Response) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetApiV1Recipes500Response struct {
}

func (response GetApiV1Recipes500Response) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostApiV1RecipesRequestObject struct {
	Params PostApiV1RecipesParams
	Body   *PostApiV1RecipesJSONRequestBody
}

type PostApiV1RecipesResponseObject interface {
	VisitPostApiV1RecipesResponse(w http.ResponseWriter) error
}

type PostApiV1Recipes201JSONResponse CreateRecipeResponse

func (response PostApiV1Recipes201JSONResponse) VisitPostApiV1RecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Recipes400Response struct {
}

func (response PostApiV1Recipes400Response) VisitPostApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteApiV1RecipesRecipeIdRequestObject struct {
	RecipeId string `json:"recipe_id"`
	Params   DeleteApiV1RecipesRecipeIdParams
}

type DeleteApiV1RecipesRecipeIdResponseObject interface {
	VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error
}

type DeleteApiV1RecipesRecipeId204Response struct {
}

func (response DeleteApiV1RecipesRecipeId204Response) VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1RecipesRecipeId400Response struct {
}

func (response DeleteApiV1RecipesRecipeId400Response) VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List recipes
	// (GET /api/v1/recipes)
	GetApiV1Recipes(ctx context.Context, request GetApiV1RecipesRequestObject) (GetApiV1RecipesResponseObject, error)
	// Create recipe
	// (POST /api/v1/recipes)
	PostApiV1Recipes(ctx context.Context, request PostApiV1RecipesRequestObject) (PostApiV1RecipesResponseObject, error)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteApiV1RecipesRecipeId(ctx context.Context, request DeleteApiV1RecipesRecipeIdRequestObject) (DeleteApiV1RecipesRecipeIdResponseObject, error)

	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiV1Recipes operation middleware
func (sh *strictHandler) GetApiV1Recipes(w http.ResponseWriter, r *http.Request, params GetApiV1RecipesParams) {
	var request GetApiV1RecipesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Recipes(ctx, request.(GetApiV1RecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Recipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1RecipesResponseObject); ok {
		if err := validResponse.VisitGetApiV1RecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Recipes operation middleware
func (sh *strictHandler) PostApiV1Recipes(w http.ResponseWriter, r *http.Request, params PostApiV1RecipesParams) {
	var request PostApiV1RecipesRequestObject

	request.Params = params

	var body PostApiV1RecipesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Recipes(ctx, request.(PostApiV1RecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Recipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1RecipesResponseObject); ok {
		if err := validResponse.VisitPostApiV1RecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1RecipesRecipeId operation middleware
func (sh *strictHandler) DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string, params DeleteApiV1RecipesRecipeIdParams) {
	var request DeleteApiV1RecipesRecipeIdRequestObject

	request.RecipeId = recipeId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1RecipesRecipeId(ctx, request.(DeleteApiV1RecipesRecipeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1RecipesRecipeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApiV1RecipesRecipeIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1RecipesRecipeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYX2/bug7/KoLuffSadHd3D3nbFty7YhtWdGcHBxiKQLGZWJssqZScNij83Q8o2Yn/",
	"JU23DuelT00livyJpH6kec9TU1ijQXvHZ/fcChQFeMDw35vS5wYv5pe0SgsZuBSl9dJoPuMXc2ZWzOfA",
	"RBDkCZe0flMCbnnCtSiAz3jcXMiMJ9ylORSCVPmtpU3nUeo1r6qEv0W4/QQ+N9kBe/+TygOy5ZYtEW5Z",
	"EWQPGCWJxU5ib/bfCCs+4/+a7O89ibtuUpgMlFvscQRYc7laybRUfvsgrGwnegBVR+BRoPYoAqiPspD+",
	"AJ5P4k4WZcF0WSwBKUQIqbTgmDcMwZeoD8BTpLWDLIOVKJXns5fTpAmZ1B7WgAHHpVjDARi01TJ+wKQV",
	"axi3eD5q8KsDvJi/B5EBDm3SLruYN7byKLYz9tcLEnhxQSmBcFNKhIzPPJYwioB7cP5F6YKKfr5WzZHw",
	"Ut4hCA9X4apXcFOC87QsskwSNKEu0VhAL8Hx2UooBwm3raV7vgSh3cjDSDqp/PgMTrouGtHfSsrH52LC",
	"ZSHWsChRDcPx2cbLsyDDpFKl8yi81OtAGzE1KD6lUmKpoAnGAKMtl0qmnejUXqxFl8YoEJpk0QjnFwo2",
	"oE680BWd+BgOUFg92BAJ6aFwj3D5Fw+WFNSQBKIIHvLS09XGOG+fhd9qsW68kh6RdQkkAL3eGTTL75B6",
	"sthNR2eNdjAMzzuzWgEEMqWI7KLRTcw9fR8pAPRI2G1uWBosZ93wDlO6SfZxQLRLKjO2MvjITHni19IF",
	"OAcvpIKMtZYbFxy+7a8+sBHPf9XypmxsMpmB9nIlx4jqH3ignRTRmUyFB8duc/A5tMPJpGPxnNqyjXRy",
	"qeCM/9Yn3bs+ZoCQMSWdpzA2LyGKJ09PAF3z8X2y5t0fZ4fQPrVbqZ+ki12oxnjjUqylpvd7VRdtev9K",
	"fV7x2bfjXmiddETPVXLf45GdMx/j1Yhj6NNqAP66Cz+AGHj8/6ABZcpsI8iwYcfkENyuho91qoRtZjTz",
	"OWVx7GKaMyMpEFurE3q1qNgCNkpXBgtB3UgptX/9ig/boiR2UUM6LRFB+6CotnCiPm+8UIvUlHoE8x+0",
	"OUAsNkJGimiZOGShn9vBb0nTDDZtaBvFWLYO+fuhErd7GKDLgixro8ni5vWUYCPoNF9YBEdoBKBpflNW",
	"wh39MCpbkDpSche2zaIQaS6DosL8EAtr2nj3HNlnigHaL1KvFQT6aapKg9yiSSOUbpqeVq6kdh7LlJbd",
	"rqaSmdFyVVIFMHrhIDU6c0fKRiPaoA3IpWbNyYOFo5VrBkdb+cDNfb1jdbadtuM8+yU36CPNthU+SLkR",
	"2TjTHsnHeafc9yKy22Ohmg2ah15ignBE3QVksix4wnOB2bHcqvnyudV7bvWeW73nVu9Iqzd0Xmf0UfPP",
	"6KMNIYr8NWQsJdc+31HWQsl17tsMVq9nAn+Qfvpz/WDSkYekXpnwER09zANyyd5YIvINoIsYp2fTs/NQ",
	"VyxoYSWf8f+cTc+mob3weYjxRFg52ZxPcN/lriF0OsSGoaJdZKFd9G+s/PP8ajfCas9HD3TEe5FJZ1hF",
	"HfED8t156wkH+iPTE470x5knHGkNG0+Q3o8Eq2vK69hfBye/nE7pT2q0h9hZCmsVkYY0evLdRR4+bS46",
	"+FQJSTIYQdZtfvPsm4hXCX8VwXRPvBX0SRDnd1XC/zsmc6E9IDGpA9wAMkA0sad1ZVEI3DafCS1j1riR",
	"/Lo07ikT7DrSCDj/1mTbJ/P02Gyz6nIWPdpqEOzz3wSh/mIbCXhNs3VnclqUO3GLhppiSHs9rpjcxx8L",
	"mVVRsQIPw9DOw3o7uPFPmD3/IouE2TaR2X6yvQN1dLLdZ9Xh+3w11gjRTX7GmfFkx5k5COXzY4T7Pko8",
	"yBwe7vzEKiF7aQR3orChQHz+MD627zUGH2i1qqq/AwAA///nMRS3CxsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
