//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/nikpivkin/roasti-app-backend/internal/api/models"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// CreateRecipeResponse Coffee brewing recipe
type CreateRecipeResponse = externalRef0.Recipe

// Page Generic paginated response
type Page struct {
	// Items List of items on this page
	Items []interface{} `json:"items"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// TotalCount Total number of items available
	TotalCount int `json:"total_count"`
}

// RecipePage defines model for RecipePage.
type RecipePage struct {
	Items []externalRef0.Recipe `json:"items"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// TotalCount Total number of items available
	TotalCount int `json:"total_count"`
}

// LimitParam defines model for LimitParam.
type LimitParam = int

// PageParam defines model for PageParam.
type PageParam = int

// UserIDHeader defines model for UserIDHeader.
type UserIDHeader = string

// GetApiV1RecipesParams defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParams struct {
	ListRecipes *externalRef0.ListRecipesParams `form:"listRecipes,omitempty" json:"listRecipes,omitempty"`

	// XUserId User ID
	XUserId UserIDHeader `json:"X-User-Id"`
}

// PostApiV1RecipesParams defines parameters for PostApiV1Recipes.
type PostApiV1RecipesParams struct {
	// XUserId User ID
	XUserId UserIDHeader `json:"X-User-Id"`
}

// DeleteApiV1RecipesRecipeIdParams defines parameters for DeleteApiV1RecipesRecipeId.
type DeleteApiV1RecipesRecipeIdParams struct {
	// XUserId User ID
	XUserId UserIDHeader `json:"X-User-Id"`
}

// PatchApiV1RecipesRecipeIdParams defines parameters for PatchApiV1RecipesRecipeId.
type PatchApiV1RecipesRecipeIdParams struct {
	// XUserId User ID
	XUserId UserIDHeader `json:"X-User-Id"`
}

// PostApiV1RecipesJSONRequestBody defines body for PostApiV1Recipes for application/json ContentType.
type PostApiV1RecipesJSONRequestBody = externalRef0.CreateRecipeRequest

// PatchApiV1RecipesRecipeIdJSONRequestBody defines body for PatchApiV1RecipesRecipeId for application/json ContentType.
type PatchApiV1RecipesRecipeIdJSONRequestBody = externalRef0.PatchRecipeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List recipes
	// (GET /api/v1/recipes)
	GetApiV1Recipes(w http.ResponseWriter, r *http.Request, params GetApiV1RecipesParams)
	// Create recipe
	// (POST /api/v1/recipes)
	PostApiV1Recipes(w http.ResponseWriter, r *http.Request, params PostApiV1RecipesParams)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string, params DeleteApiV1RecipesRecipeIdParams)
	// Update recipe
	// (PATCH /api/v1/recipes/{recipe_id})
	PatchApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string, params PatchApiV1RecipesRecipeIdParams)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1Recipes operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Recipes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1RecipesParams

	// ------------- Optional query parameter "listRecipes" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "listRecipes", r.URL.Query(), &params.ListRecipes, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listRecipes", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Recipes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Recipes operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Recipes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiV1RecipesParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Recipes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1RecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiV1RecipesRecipeIdParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1RecipesRecipeId(w, r, recipeId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiV1RecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchApiV1RecipesRecipeIdParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiV1RecipesRecipeId(w, r, recipeId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes", wrapper.GetApiV1Recipes)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/recipes", wrapper.PostApiV1Recipes)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.DeleteApiV1RecipesRecipeId)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.PatchApiV1RecipesRecipeId)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}

type GetApiV1RecipesRequestObject struct {
	Params GetApiV1RecipesParams
}

type GetApiV1RecipesResponseObject interface {
	VisitGetApiV1RecipesResponse(w http.ResponseWriter) error
}

type GetApiV1Recipes200JSONResponse RecipePage

func (response GetApiV1Recipes200JSONResponse) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Recipes400Response struct {
}

func (response GetApiV1Recipes400Response) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetApiV1Recipes500Response struct {
}

func (response GetApiV1Recipes500Response) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostApiV1RecipesRequestObject struct {
	Params PostApiV1RecipesParams
	Body   *PostApiV1RecipesJSONRequestBody
}

type PostApiV1RecipesResponseObject interface {
	VisitPostApiV1RecipesResponse(w http.ResponseWriter) error
}

type PostApiV1Recipes201JSONResponse CreateRecipeResponse

func (response PostApiV1Recipes201JSONResponse) VisitPostApiV1RecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Recipes400Response struct {
}

func (response PostApiV1Recipes400Response) VisitPostApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteApiV1RecipesRecipeIdRequestObject struct {
	RecipeId string `json:"recipe_id"`
	Params   DeleteApiV1RecipesRecipeIdParams
}

type DeleteApiV1RecipesRecipeIdResponseObject interface {
	VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error
}

type DeleteApiV1RecipesRecipeId204Response struct {
}

func (response DeleteApiV1RecipesRecipeId204Response) VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1RecipesRecipeId400Response struct {
}

func (response DeleteApiV1RecipesRecipeId400Response) VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PatchApiV1RecipesRecipeIdRequestObject struct {
	RecipeId string `json:"recipe_id"`
	Params   PatchApiV1RecipesRecipeIdParams
	Body     *PatchApiV1RecipesRecipeIdJSONRequestBody
}

type PatchApiV1RecipesRecipeIdResponseObject interface {
	VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error
}

type PatchApiV1RecipesRecipeId200JSONResponse externalRef0.Recipe

func (response PatchApiV1RecipesRecipeId200JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiV1RecipesRecipeId400JSONResponse externalRef0.ApiErrorResponse

func (response PatchApiV1RecipesRecipeId400JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiV1RecipesRecipeId403JSONResponse externalRef0.ApiErrorResponse

func (response PatchApiV1RecipesRecipeId403JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiV1RecipesRecipeId404JSONResponse externalRef0.ApiErrorResponse

func (response PatchApiV1RecipesRecipeId404JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List recipes
	// (GET /api/v1/recipes)
	GetApiV1Recipes(ctx context.Context, request GetApiV1RecipesRequestObject) (GetApiV1RecipesResponseObject, error)
	// Create recipe
	// (POST /api/v1/recipes)
	PostApiV1Recipes(ctx context.Context, request PostApiV1RecipesRequestObject) (PostApiV1RecipesResponseObject, error)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteApiV1RecipesRecipeId(ctx context.Context, request DeleteApiV1RecipesRecipeIdRequestObject) (DeleteApiV1RecipesRecipeIdResponseObject, error)
	// Update recipe
	// (PATCH /api/v1/recipes/{recipe_id})
	PatchApiV1RecipesRecipeId(ctx context.Context, request PatchApiV1RecipesRecipeIdRequestObject) (PatchApiV1RecipesRecipeIdResponseObject, error)

	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiV1Recipes operation middleware
func (sh *strictHandler) GetApiV1Recipes(w http.ResponseWriter, r *http.Request, params GetApiV1RecipesParams) {
	var request GetApiV1RecipesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Recipes(ctx, request.(GetApiV1RecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Recipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1RecipesResponseObject); ok {
		if err := validResponse.VisitGetApiV1RecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Recipes operation middleware
func (sh *strictHandler) PostApiV1Recipes(w http.ResponseWriter, r *http.Request, params PostApiV1RecipesParams) {
	var request PostApiV1RecipesRequestObject

	request.Params = params

	var body PostApiV1RecipesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Recipes(ctx, request.(PostApiV1RecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Recipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1RecipesResponseObject); ok {
		if err := validResponse.VisitPostApiV1RecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1RecipesRecipeId operation middleware
func (sh *strictHandler) DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string, params DeleteApiV1RecipesRecipeIdParams) {
	var request DeleteApiV1RecipesRecipeIdRequestObject

	request.RecipeId = recipeId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1RecipesRecipeId(ctx, request.(DeleteApiV1RecipesRecipeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1RecipesRecipeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApiV1RecipesRecipeIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1RecipesRecipeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchApiV1RecipesRecipeId operation middleware
func (sh *strictHandler) PatchApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string, params PatchApiV1RecipesRecipeIdParams) {
	var request PatchApiV1RecipesRecipeIdRequestObject

	request.RecipeId = recipeId
	request.Params = params

	var body PatchApiV1RecipesRecipeIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchApiV1RecipesRecipeId(ctx, request.(PatchApiV1RecipesRecipeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchApiV1RecipesRecipeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchApiV1RecipesRecipeIdResponseObject); ok {
		if err := validResponse.VisitPatchApiV1RecipesRecipeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW2/bOBb+KwR3H3YBJXba7D74rW1mpkHTSdBOZwYoAoMWjy22FMmQlBMj0H8fkJRk",
	"XWjFTd0Wg8mTZV4OD893Lh/Je5zKXEkBwho8u8eKaJKDBe3/XbCc2SvX5P5RMKlmyjIp8Ay/JXcsL3Ik",
	"inwBGskl0pAyBQZZiTTYQgucYOaG3hSgNzjBguSAZ5g7qTjBJs0gJ0HykhTc4tmzaYLtRrlRTFhYgcZl",
	"meArsoIdariu1uI7llRkBfEVT6ILfjCgz89eA6Ggh2u6XnR+Vq+VhWHNYn8euQFH5xQnWMNNwTRQPLO6",
	"gKgG2IKxR4XxIipdjNVMrLwquaTAzfyCGfsu7NFbwuMDd4pLCrXwuLGbeR0DEM4vl3j28R7/W8MSz/C/",
	"JltPmIRxZlItfkVWTBC/+zK5x0pLBdoy8EqQwmZSn9OhnX5m3IJGiw0KY4b7S/BCw+1bsJn08/fQ5eV2",
	"QplgypZLlhbcbvacfrad4Kxb6SMXnyC1uLwuE2zshru2pdS5H1NJcAu80kAsBHu+A6OkMDDc9yu5XAIg",
	"tzUmVpVr4iRqtzmLGO78zLm0zQA5t0C3mUSpX5n6xkbg0JpAhNmtkOt1IilaSt0VJQrOyYI3vhQFap4/",
	"HqlqA3Nih/r9xnIwluQK3WYgWoqhW2LqrePEQ+LmY0osHFmWR43Qkd1f6gwsYRwoajXXxt5t169yswTH",
	"MP4g2E3R7JNREJYtGUSDhOVkBfNC86GYS/9BOPJjEOO8MFYT6xzvywBWxYKzNOKMgrKUWDAOHJtB23EQ",
	"MyjM4xu0ZoYtOBxvd7CQkgNxSQNrSYydc1gD39OE79yMCz/BRyWoiGdfagoaKHJpzsFYx1wYnmBmIaTK",
	"Pf31vQWFt3mBaE08gpZZHon0kAlQ6I3YtFD0kU7PibGomr6n55ftcvPROV3SSjL1Hrrx0Y3rjqPXNm88",
	"43qQLkNlHm7tFxCgWYpUqBtAka6TZT8LNgB1JVxUePpuJJ15nKuFMl7PieAUuMUeZCUIVqBroY2FmbB4",
	"SAqSwCGGqbXQGoT1Uirx+wiz0hI+T2UhYp7hOge6kjVhIYIflN/3BG+vpGZBNf9q6xDDNjh3jfB+hMGP",
	"HnKEBuUvicew/jAa42W7mvRCsZ+0lrpdnbu6gOseGv11kRNxpIFQZ2PkR6EcjAlGG4+1IDNmxGEtfIgu",
	"NLEIosidcCGF02D9/6lDXoNIs7nSYBykBLSsv5314M59SE7nTpwTcue75Twnaca8oFx+JnMl26BvM1Y/",
	"Fw60fc/EioNPsHXdrDVXWqZBla7F9yvITBiri9Q1m4afuGWiBbnQno/ODaRSUDNSGOuhtbZecyZQPXNn",
	"aWyFq9TRg4CvPn25MSbRjvx4JXmfSW1DIWkLfNDzgmbx5D7ij10ie1OA8XmIUMqC2a5aCC4JN9AHtaGa",
	"B2eKPXc5OBn73mSqOudVVuyu+EdDqZgZ4VTfllIdnCSNu+wjeciIN591PKKXX5o+5E01IPu9NAvEuDVz",
	"oKzIcYIzoulYpmydjQelpsVGRi442tRi9FZi1/aviE2zg8TyNz8Ffs/YfvSJ50cG5UgM7YK/4klP1xBP",
	"1xBP1xBP1xD/xGuIIVadG/aqtEezkfeIQA2GZICzlc0aNjDnbJXZNjmo2inRn51893P9oI87CzGxlD7L",
	"B0Cx15yhF8ox/jVoE3ScHk+PT/wBRIEgiuEZfn48PZ76w7zNvEtNiGKT9cmkfgGZ3eMVeKBdmvfM5Jz6",
	"Sxn7QrHfT7avAe3Hnh3n+u2QSedNxB3xHxi/8+GivHYeEo7nXt1n06n7SaWwEO5DiFLcRTuTYvLJhAS6",
	"fbsYC6LWpYU39OC1qLqQqiO1tlqZ4NOgRnfGS0KRrkhVmeD/xcacCwvaJT8Deg063B2Ep4Miz4ne1Bda",
	"rcWUNBGMrqQ5JEjXIRTB2JeSbg5m45EzZNkNf+f/5QDtk4NpEn2PieBeJci6hO8Fdge+sFBdxlxfL+wm",
	"9+FjzmgZBHOwMET4zLe3MQ4//rXwKwPSv/+5vLB9/muUGn2L7CeoYYCexiiM28ljjBlmNsb0uSzNItHg",
	"mv8OpvpmIRY52e0VYdNDK1Lfxe4MrZojbL3hkMsPbnUjivQy9en0+Y/Q4ldpEeFc3gJF/xHuj6c+/w0q",
	"nf4IlSqEnDJLWQjai8YPHrlOasuAcJuNMYnXYcSDjmfhzk4UJ6y3NbgjufLM5/INjjKkHsF+41rLsvwr",
	"AAD//zAvIX6xIgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
