// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	externalRef0 "github.com/nikpivkin/roasti-app-backend/internal/api/models"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for GetApiV1RecipesParamsListRecipesSortDirection.
const (
	Asc  GetApiV1RecipesParamsListRecipesSortDirection = "asc"
	Desc GetApiV1RecipesParamsListRecipesSortDirection = "desc"
)

// Valid indicates whether the value is a known member of the GetApiV1RecipesParamsListRecipesSortDirection enum.
func (e GetApiV1RecipesParamsListRecipesSortDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1RecipesParamsListRecipesSortField.
const (
	CreatedAt GetApiV1RecipesParamsListRecipesSortField = "created_at"
	Title     GetApiV1RecipesParamsListRecipesSortField = "title"
)

// Valid indicates whether the value is a known member of the GetApiV1RecipesParamsListRecipesSortField enum.
func (e GetApiV1RecipesParamsListRecipesSortField) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// CreateRecipeResponse Coffee brewing recipe
type CreateRecipeResponse = externalRef0.Recipe

// Page Generic paginated response
type Page struct {
	// Items List of items on this page
	Items []interface{} `json:"items"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// TotalCount Total number of items available
	TotalCount int `json:"total_count"`
}

// RecipePage defines model for RecipePage.
type RecipePage struct {
	Items []externalRef0.Recipe `json:"items"`

	// Limit Maximum number of items per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// TotalCount Total number of items available
	TotalCount int `json:"total_count"`
}

// UpdateRecipeResponse Coffee brewing recipe
type UpdateRecipeResponse = externalRef0.Recipe

// GetApiV1RecipesParams defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParams struct {
	ListRecipes *externalRef0.ListRecipesParams `form:"listRecipes,omitempty" json:"listRecipes,omitempty"`
}

// GetApiV1RecipesParamsListRecipesSortDirection defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParamsListRecipesSortDirection string

// GetApiV1RecipesParamsListRecipesSortField defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParamsListRecipesSortField string

// PostApiV1UploadsImagesMultipartBody defines parameters for PostApiV1UploadsImages.
type PostApiV1UploadsImagesMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PostApiV1AuthLoginJSONRequestBody defines body for PostApiV1AuthLogin for application/json ContentType.
type PostApiV1AuthLoginJSONRequestBody = externalRef0.LoginRequest

// PostApiV1AuthRefreshJSONRequestBody defines body for PostApiV1AuthRefresh for application/json ContentType.
type PostApiV1AuthRefreshJSONRequestBody = externalRef0.RefreshRequest

// PostApiV1AuthRegisterJSONRequestBody defines body for PostApiV1AuthRegister for application/json ContentType.
type PostApiV1AuthRegisterJSONRequestBody = externalRef0.RegisterRequest

// PostApiV1RecipesJSONRequestBody defines body for PostApiV1Recipes for application/json ContentType.
type PostApiV1RecipesJSONRequestBody = externalRef0.CreateRecipeRequest

// PatchApiV1RecipesRecipeIdJSONRequestBody defines body for PatchApiV1RecipesRecipeId for application/json ContentType.
type PatchApiV1RecipesRecipeIdJSONRequestBody = externalRef0.PatchRecipeRequest

// PutApiV1RecipesRecipeIdJSONRequestBody defines body for PutApiV1RecipesRecipeId for application/json ContentType.
type PutApiV1RecipesRecipeIdJSONRequestBody = externalRef0.UpdateRecipeRequest

// PostApiV1UploadsImagesMultipartRequestBody defines body for PostApiV1UploadsImages for multipart/form-data ContentType.
type PostApiV1UploadsImagesMultipartRequestBody PostApiV1UploadsImagesMultipartBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiV1AuthLoginWithBody request with any body
	PostApiV1AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1AuthLogin(ctx context.Context, body PostApiV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1AuthLogout request
	PostApiV1AuthLogout(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1AuthRefreshWithBody request with any body
	PostApiV1AuthRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1AuthRefresh(ctx context.Context, body PostApiV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1AuthRegisterWithBody request with any body
	PostApiV1AuthRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1AuthRegister(ctx context.Context, body PostApiV1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ProfilesMe request
	GetApiV1ProfilesMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Recipes request
	GetApiV1Recipes(ctx context.Context, params *GetApiV1RecipesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1RecipesWithBody request with any body
	PostApiV1RecipesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1Recipes(ctx context.Context, body PostApiV1RecipesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiV1RecipesRecipeId request
	DeleteApiV1RecipesRecipeId(ctx context.Context, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchApiV1RecipesRecipeIdWithBody request with any body
	PatchApiV1RecipesRecipeIdWithBody(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchApiV1RecipesRecipeId(ctx context.Context, recipeId string, body PatchApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiV1RecipesRecipeIdWithBody request with any body
	PutApiV1RecipesRecipeIdWithBody(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiV1RecipesRecipeId(ctx context.Context, recipeId string, body PutApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1UploadsImagesWithBody request with any body
	PostApiV1UploadsImagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1UploadsImagesImageId request
	GetApiV1UploadsImagesImageId(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiV1AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AuthLogin(ctx context.Context, body PostApiV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AuthLogout(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthLogoutRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AuthRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthRefreshRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AuthRefresh(ctx context.Context, body PostApiV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthRefreshRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AuthRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthRegisterRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1AuthRegister(ctx context.Context, body PostApiV1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1AuthRegisterRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1ProfilesMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ProfilesMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Recipes(ctx context.Context, params *GetApiV1RecipesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1RecipesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1RecipesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RecipesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1Recipes(ctx context.Context, body PostApiV1RecipesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1RecipesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiV1RecipesRecipeId(ctx context.Context, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiV1RecipesRecipeIdRequest(c.Server, recipeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchApiV1RecipesRecipeIdWithBody(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchApiV1RecipesRecipeIdRequestWithBody(c.Server, recipeId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchApiV1RecipesRecipeId(ctx context.Context, recipeId string, body PatchApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchApiV1RecipesRecipeIdRequest(c.Server, recipeId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1RecipesRecipeIdWithBody(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1RecipesRecipeIdRequestWithBody(c.Server, recipeId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1RecipesRecipeId(ctx context.Context, recipeId string, body PutApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1RecipesRecipeIdRequest(c.Server, recipeId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1UploadsImagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1UploadsImagesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1UploadsImagesImageId(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1UploadsImagesImageIdRequest(c.Server, imageId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiV1AuthLoginRequest calls the generic PostApiV1AuthLogin builder with application/json body
func NewPostApiV1AuthLoginRequest(server string, body PostApiV1AuthLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1AuthLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1AuthLoginRequestWithBody generates requests for PostApiV1AuthLogin with any type of body
func NewPostApiV1AuthLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV1AuthLogoutRequest generates requests for PostApiV1AuthLogout
func NewPostApiV1AuthLogoutRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/logout")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1AuthRefreshRequest calls the generic PostApiV1AuthRefresh builder with application/json body
func NewPostApiV1AuthRefreshRequest(server string, body PostApiV1AuthRefreshJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1AuthRefreshRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1AuthRefreshRequestWithBody generates requests for PostApiV1AuthRefresh with any type of body
func NewPostApiV1AuthRefreshRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV1AuthRegisterRequest calls the generic PostApiV1AuthRegister builder with application/json body
func NewPostApiV1AuthRegisterRequest(server string, body PostApiV1AuthRegisterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1AuthRegisterRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1AuthRegisterRequestWithBody generates requests for PostApiV1AuthRegister with any type of body
func NewPostApiV1AuthRegisterRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1ProfilesMeRequest generates requests for GetApiV1ProfilesMe
func NewGetApiV1ProfilesMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/profiles/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1RecipesRequest generates requests for GetApiV1Recipes
func NewGetApiV1RecipesRequest(server string, params *GetApiV1RecipesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/recipes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ListRecipes != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "listRecipes", *params.ListRecipes, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1RecipesRequest calls the generic PostApiV1Recipes builder with application/json body
func NewPostApiV1RecipesRequest(server string, body PostApiV1RecipesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1RecipesRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1RecipesRequestWithBody generates requests for PostApiV1Recipes with any type of body
func NewPostApiV1RecipesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/recipes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiV1RecipesRecipeIdRequest generates requests for DeleteApiV1RecipesRecipeId
func NewDeleteApiV1RecipesRecipeIdRequest(server string, recipeId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "recipe_id", recipeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/recipes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchApiV1RecipesRecipeIdRequest calls the generic PatchApiV1RecipesRecipeId builder with application/json body
func NewPatchApiV1RecipesRecipeIdRequest(server string, recipeId string, body PatchApiV1RecipesRecipeIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchApiV1RecipesRecipeIdRequestWithBody(server, recipeId, "application/json", bodyReader)
}

// NewPatchApiV1RecipesRecipeIdRequestWithBody generates requests for PatchApiV1RecipesRecipeId with any type of body
func NewPatchApiV1RecipesRecipeIdRequestWithBody(server string, recipeId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "recipe_id", recipeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/recipes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutApiV1RecipesRecipeIdRequest calls the generic PutApiV1RecipesRecipeId builder with application/json body
func NewPutApiV1RecipesRecipeIdRequest(server string, recipeId string, body PutApiV1RecipesRecipeIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiV1RecipesRecipeIdRequestWithBody(server, recipeId, "application/json", bodyReader)
}

// NewPutApiV1RecipesRecipeIdRequestWithBody generates requests for PutApiV1RecipesRecipeId with any type of body
func NewPutApiV1RecipesRecipeIdRequestWithBody(server string, recipeId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "recipe_id", recipeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/recipes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiV1UploadsImagesRequestWithBody generates requests for PostApiV1UploadsImages with any type of body
func NewPostApiV1UploadsImagesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/uploads/images")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1UploadsImagesImageIdRequest generates requests for GetApiV1UploadsImagesImageId
func NewGetApiV1UploadsImagesImageIdRequest(server string, imageId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "image_id", imageId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/uploads/images/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiV1AuthLoginWithBodyWithResponse request with any body
	PostApiV1AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AuthLoginResponse, error)

	PostApiV1AuthLoginWithResponse(ctx context.Context, body PostApiV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AuthLoginResponse, error)

	// PostApiV1AuthLogoutWithResponse request
	PostApiV1AuthLogoutWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV1AuthLogoutResponse, error)

	// PostApiV1AuthRefreshWithBodyWithResponse request with any body
	PostApiV1AuthRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AuthRefreshResponse, error)

	PostApiV1AuthRefreshWithResponse(ctx context.Context, body PostApiV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AuthRefreshResponse, error)

	// PostApiV1AuthRegisterWithBodyWithResponse request with any body
	PostApiV1AuthRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AuthRegisterResponse, error)

	PostApiV1AuthRegisterWithResponse(ctx context.Context, body PostApiV1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AuthRegisterResponse, error)

	// GetApiV1ProfilesMeWithResponse request
	GetApiV1ProfilesMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1ProfilesMeResponse, error)

	// GetApiV1RecipesWithResponse request
	GetApiV1RecipesWithResponse(ctx context.Context, params *GetApiV1RecipesParams, reqEditors ...RequestEditorFn) (*GetApiV1RecipesResponse, error)

	// PostApiV1RecipesWithBodyWithResponse request with any body
	PostApiV1RecipesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RecipesResponse, error)

	PostApiV1RecipesWithResponse(ctx context.Context, body PostApiV1RecipesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RecipesResponse, error)

	// DeleteApiV1RecipesRecipeIdWithResponse request
	DeleteApiV1RecipesRecipeIdWithResponse(ctx context.Context, recipeId string, reqEditors ...RequestEditorFn) (*DeleteApiV1RecipesRecipeIdResponse, error)

	// PatchApiV1RecipesRecipeIdWithBodyWithResponse request with any body
	PatchApiV1RecipesRecipeIdWithBodyWithResponse(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchApiV1RecipesRecipeIdResponse, error)

	PatchApiV1RecipesRecipeIdWithResponse(ctx context.Context, recipeId string, body PatchApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchApiV1RecipesRecipeIdResponse, error)

	// PutApiV1RecipesRecipeIdWithBodyWithResponse request with any body
	PutApiV1RecipesRecipeIdWithBodyWithResponse(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1RecipesRecipeIdResponse, error)

	PutApiV1RecipesRecipeIdWithResponse(ctx context.Context, recipeId string, body PutApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1RecipesRecipeIdResponse, error)

	// PostApiV1UploadsImagesWithBodyWithResponse request with any body
	PostApiV1UploadsImagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1UploadsImagesResponse, error)

	// GetApiV1UploadsImagesImageIdWithResponse request
	GetApiV1UploadsImagesImageIdWithResponse(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*GetApiV1UploadsImagesImageIdResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type PostApiV1AuthLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.AuthResponse
	JSON400      *externalRef0.ApiErrorResponse
	JSON401      *externalRef0.ApiErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1AuthLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1AuthLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1AuthLogoutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiV1AuthLogoutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1AuthLogoutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1AuthRefreshResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.TokensResponse
	JSON401      *externalRef0.ApiErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1AuthRefreshResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1AuthRefreshResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1AuthRegisterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *externalRef0.AuthResponse
	JSON400      *externalRef0.ApiErrorResponse
	JSON409      *externalRef0.ApiErrorResponse
	JSON422      *externalRef0.ApiErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1AuthRegisterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1AuthRegisterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1ProfilesMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.MyProfile
}

// Status returns HTTPResponse.Status
func (r GetApiV1ProfilesMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ProfilesMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1RecipesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecipePage
}

// Status returns HTTPResponse.Status
func (r GetApiV1RecipesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1RecipesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1RecipesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateRecipeResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1RecipesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1RecipesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiV1RecipesRecipeIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteApiV1RecipesRecipeIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiV1RecipesRecipeIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchApiV1RecipesRecipeIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.Recipe
	JSON400      *externalRef0.ApiErrorResponse
	JSON403      *externalRef0.ApiErrorResponse
	JSON404      *externalRef0.ApiErrorResponse
}

// Status returns HTTPResponse.Status
func (r PatchApiV1RecipesRecipeIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchApiV1RecipesRecipeIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutApiV1RecipesRecipeIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UpdateRecipeResponse
	JSON400      *externalRef0.ApiErrorResponse
	JSON403      *externalRef0.ApiErrorResponse
	JSON404      *externalRef0.ApiErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutApiV1RecipesRecipeIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiV1RecipesRecipeIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1UploadsImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *externalRef0.Image
}

// Status returns HTTPResponse.Status
func (r PostApiV1UploadsImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1UploadsImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1UploadsImagesImageIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetApiV1UploadsImagesImageIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1UploadsImagesImageIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiV1AuthLoginWithBodyWithResponse request with arbitrary body returning *PostApiV1AuthLoginResponse
func (c *ClientWithResponses) PostApiV1AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AuthLoginResponse, error) {
	rsp, err := c.PostApiV1AuthLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthLoginResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1AuthLoginWithResponse(ctx context.Context, body PostApiV1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AuthLoginResponse, error) {
	rsp, err := c.PostApiV1AuthLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthLoginResponse(rsp)
}

// PostApiV1AuthLogoutWithResponse request returning *PostApiV1AuthLogoutResponse
func (c *ClientWithResponses) PostApiV1AuthLogoutWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV1AuthLogoutResponse, error) {
	rsp, err := c.PostApiV1AuthLogout(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthLogoutResponse(rsp)
}

// PostApiV1AuthRefreshWithBodyWithResponse request with arbitrary body returning *PostApiV1AuthRefreshResponse
func (c *ClientWithResponses) PostApiV1AuthRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AuthRefreshResponse, error) {
	rsp, err := c.PostApiV1AuthRefreshWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthRefreshResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1AuthRefreshWithResponse(ctx context.Context, body PostApiV1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AuthRefreshResponse, error) {
	rsp, err := c.PostApiV1AuthRefresh(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthRefreshResponse(rsp)
}

// PostApiV1AuthRegisterWithBodyWithResponse request with arbitrary body returning *PostApiV1AuthRegisterResponse
func (c *ClientWithResponses) PostApiV1AuthRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1AuthRegisterResponse, error) {
	rsp, err := c.PostApiV1AuthRegisterWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthRegisterResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1AuthRegisterWithResponse(ctx context.Context, body PostApiV1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1AuthRegisterResponse, error) {
	rsp, err := c.PostApiV1AuthRegister(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1AuthRegisterResponse(rsp)
}

// GetApiV1ProfilesMeWithResponse request returning *GetApiV1ProfilesMeResponse
func (c *ClientWithResponses) GetApiV1ProfilesMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1ProfilesMeResponse, error) {
	rsp, err := c.GetApiV1ProfilesMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ProfilesMeResponse(rsp)
}

// GetApiV1RecipesWithResponse request returning *GetApiV1RecipesResponse
func (c *ClientWithResponses) GetApiV1RecipesWithResponse(ctx context.Context, params *GetApiV1RecipesParams, reqEditors ...RequestEditorFn) (*GetApiV1RecipesResponse, error) {
	rsp, err := c.GetApiV1Recipes(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1RecipesResponse(rsp)
}

// PostApiV1RecipesWithBodyWithResponse request with arbitrary body returning *PostApiV1RecipesResponse
func (c *ClientWithResponses) PostApiV1RecipesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1RecipesResponse, error) {
	rsp, err := c.PostApiV1RecipesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RecipesResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1RecipesWithResponse(ctx context.Context, body PostApiV1RecipesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1RecipesResponse, error) {
	rsp, err := c.PostApiV1Recipes(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1RecipesResponse(rsp)
}

// DeleteApiV1RecipesRecipeIdWithResponse request returning *DeleteApiV1RecipesRecipeIdResponse
func (c *ClientWithResponses) DeleteApiV1RecipesRecipeIdWithResponse(ctx context.Context, recipeId string, reqEditors ...RequestEditorFn) (*DeleteApiV1RecipesRecipeIdResponse, error) {
	rsp, err := c.DeleteApiV1RecipesRecipeId(ctx, recipeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiV1RecipesRecipeIdResponse(rsp)
}

// PatchApiV1RecipesRecipeIdWithBodyWithResponse request with arbitrary body returning *PatchApiV1RecipesRecipeIdResponse
func (c *ClientWithResponses) PatchApiV1RecipesRecipeIdWithBodyWithResponse(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchApiV1RecipesRecipeIdResponse, error) {
	rsp, err := c.PatchApiV1RecipesRecipeIdWithBody(ctx, recipeId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchApiV1RecipesRecipeIdResponse(rsp)
}

func (c *ClientWithResponses) PatchApiV1RecipesRecipeIdWithResponse(ctx context.Context, recipeId string, body PatchApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchApiV1RecipesRecipeIdResponse, error) {
	rsp, err := c.PatchApiV1RecipesRecipeId(ctx, recipeId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchApiV1RecipesRecipeIdResponse(rsp)
}

// PutApiV1RecipesRecipeIdWithBodyWithResponse request with arbitrary body returning *PutApiV1RecipesRecipeIdResponse
func (c *ClientWithResponses) PutApiV1RecipesRecipeIdWithBodyWithResponse(ctx context.Context, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1RecipesRecipeIdResponse, error) {
	rsp, err := c.PutApiV1RecipesRecipeIdWithBody(ctx, recipeId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1RecipesRecipeIdResponse(rsp)
}

func (c *ClientWithResponses) PutApiV1RecipesRecipeIdWithResponse(ctx context.Context, recipeId string, body PutApiV1RecipesRecipeIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1RecipesRecipeIdResponse, error) {
	rsp, err := c.PutApiV1RecipesRecipeId(ctx, recipeId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1RecipesRecipeIdResponse(rsp)
}

// PostApiV1UploadsImagesWithBodyWithResponse request with arbitrary body returning *PostApiV1UploadsImagesResponse
func (c *ClientWithResponses) PostApiV1UploadsImagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1UploadsImagesResponse, error) {
	rsp, err := c.PostApiV1UploadsImagesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1UploadsImagesResponse(rsp)
}

// GetApiV1UploadsImagesImageIdWithResponse request returning *GetApiV1UploadsImagesImageIdResponse
func (c *ClientWithResponses) GetApiV1UploadsImagesImageIdWithResponse(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*GetApiV1UploadsImagesImageIdResponse, error) {
	rsp, err := c.GetApiV1UploadsImagesImageId(ctx, imageId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1UploadsImagesImageIdResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParsePostApiV1AuthLoginResponse parses an HTTP response from a PostApiV1AuthLoginWithResponse call
func ParsePostApiV1AuthLoginResponse(rsp *http.Response) (*PostApiV1AuthLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1AuthLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.AuthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParsePostApiV1AuthLogoutResponse parses an HTTP response from a PostApiV1AuthLogoutWithResponse call
func ParsePostApiV1AuthLogoutResponse(rsp *http.Response) (*PostApiV1AuthLogoutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1AuthLogoutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostApiV1AuthRefreshResponse parses an HTTP response from a PostApiV1AuthRefreshWithResponse call
func ParsePostApiV1AuthRefreshResponse(rsp *http.Response) (*PostApiV1AuthRefreshResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1AuthRefreshResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.TokensResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParsePostApiV1AuthRegisterResponse parses an HTTP response from a PostApiV1AuthRegisterWithResponse call
func ParsePostApiV1AuthRegisterResponse(rsp *http.Response) (*PostApiV1AuthRegisterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1AuthRegisterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest externalRef0.AuthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetApiV1ProfilesMeResponse parses an HTTP response from a GetApiV1ProfilesMeWithResponse call
func ParseGetApiV1ProfilesMeResponse(rsp *http.Response) (*GetApiV1ProfilesMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ProfilesMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.MyProfile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV1RecipesResponse parses an HTTP response from a GetApiV1RecipesWithResponse call
func ParseGetApiV1RecipesResponse(rsp *http.Response) (*GetApiV1RecipesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1RecipesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecipePage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiV1RecipesResponse parses an HTTP response from a PostApiV1RecipesWithResponse call
func ParsePostApiV1RecipesResponse(rsp *http.Response) (*PostApiV1RecipesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1RecipesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateRecipeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteApiV1RecipesRecipeIdResponse parses an HTTP response from a DeleteApiV1RecipesRecipeIdWithResponse call
func ParseDeleteApiV1RecipesRecipeIdResponse(rsp *http.Response) (*DeleteApiV1RecipesRecipeIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiV1RecipesRecipeIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePatchApiV1RecipesRecipeIdResponse parses an HTTP response from a PatchApiV1RecipesRecipeIdWithResponse call
func ParsePatchApiV1RecipesRecipeIdResponse(rsp *http.Response) (*PatchApiV1RecipesRecipeIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchApiV1RecipesRecipeIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.Recipe
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePutApiV1RecipesRecipeIdResponse parses an HTTP response from a PutApiV1RecipesRecipeIdWithResponse call
func ParsePutApiV1RecipesRecipeIdResponse(rsp *http.Response) (*PutApiV1RecipesRecipeIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiV1RecipesRecipeIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UpdateRecipeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ApiErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostApiV1UploadsImagesResponse parses an HTTP response from a PostApiV1UploadsImagesWithResponse call
func ParsePostApiV1UploadsImagesResponse(rsp *http.Response) (*PostApiV1UploadsImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1UploadsImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest externalRef0.Image
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetApiV1UploadsImagesImageIdResponse parses an HTTP response from a GetApiV1UploadsImagesImageIdWithResponse call
func ParseGetApiV1UploadsImagesImageIdResponse(rsp *http.Response) (*GetApiV1UploadsImagesImageIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1UploadsImagesImageIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
