- name: Setup
  hosts: all
  become: yes
  vars:
    app_user: roasti
    app_dir: /var/lib/roasti

  tasks:
    - name: Update apt repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Create user
      user:
        name: "{{ app_user }}"
        system: yes
        shell: /bin/bash

    - name: Create directories
      file:
        path: "{{ app_dir }}/uploads"
        state: directory
        owner: "{{ app_user }}"
        recurse: yes

    - name: Setup sudoers
      copy:
        content: "{{ app_user }} ALL=(ALL) NOPASSWD: ALL\n"
        dest: "/etc/sudoers.d/{{ app_user }}"
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s

    - name: Add CI deploy key
      authorized_key:
        user: "{{ app_user }}"
        key: "{{ lookup('file', '~/.ssh/roasti_deploy.pub') }}"
        state: present