//go:build go1.22

// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/nikpivkin/roasti-app-backend/internal/api/models"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for ListRecipesParamsListRecipesSortDirection.
const (
	ListRecipesParamsListRecipesSortDirectionAsc  ListRecipesParamsListRecipesSortDirection = "asc"
	ListRecipesParamsListRecipesSortDirectionDesc ListRecipesParamsListRecipesSortDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListRecipesParamsListRecipesSortDirection enum.
func (e ListRecipesParamsListRecipesSortDirection) Valid() bool {
	switch e {
	case ListRecipesParamsListRecipesSortDirectionAsc:
		return true
	case ListRecipesParamsListRecipesSortDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListRecipesParamsListRecipesSortField.
const (
	CreatedAt ListRecipesParamsListRecipesSortField = "created_at"
	Title     ListRecipesParamsListRecipesSortField = "title"
)

// Valid indicates whether the value is a known member of the ListRecipesParamsListRecipesSortField enum.
func (e ListRecipesParamsListRecipesSortField) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// Defines values for ListUserLikesParamsListUserLikesSortDirection.
const (
	ListUserLikesParamsListUserLikesSortDirectionAsc  ListUserLikesParamsListUserLikesSortDirection = "asc"
	ListUserLikesParamsListUserLikesSortDirectionDesc ListUserLikesParamsListUserLikesSortDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListUserLikesParamsListUserLikesSortDirection enum.
func (e ListUserLikesParamsListUserLikesSortDirection) Valid() bool {
	switch e {
	case ListUserLikesParamsListUserLikesSortDirectionAsc:
		return true
	case ListUserLikesParamsListUserLikesSortDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListUserLikesParamsListUserLikesType.
const (
	Recipe ListUserLikesParamsListUserLikesType = "recipe"
)

// Valid indicates whether the value is a known member of the ListUserLikesParamsListUserLikesType enum.
func (e ListUserLikesParamsListUserLikesType) Valid() bool {
	switch e {
	case Recipe:
		return true
	default:
		return false
	}
}

// LikedRecipePage defines model for LikedRecipePage.
type LikedRecipePage struct {
	Items      []externalRef0.LikedRecipe  `json:"items"`
	Pagination externalRef0.PaginationMeta `json:"pagination"`
}

// RecipePage defines model for RecipePage.
type RecipePage struct {
	Items      []externalRef0.Recipe       `json:"items"`
	Pagination externalRef0.PaginationMeta `json:"pagination"`
}

// ListRecipesParams defines parameters for ListRecipes.
type ListRecipesParams struct {
	ListRecipes *externalRef0.ListRecipesParams `form:"listRecipes,omitempty" json:"listRecipes,omitempty"`
}

// ListRecipesParamsListRecipesSortDirection defines parameters for ListRecipes.
type ListRecipesParamsListRecipesSortDirection string

// ListRecipesParamsListRecipesSortField defines parameters for ListRecipes.
type ListRecipesParamsListRecipesSortField string

// UploadImageMultipartBody defines parameters for UploadImage.
type UploadImageMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListUserLikesParams defines parameters for ListUserLikes.
type ListUserLikesParams struct {
	ListUserLikes *externalRef0.ListUserLikesParams `form:"listUserLikes,omitempty" json:"listUserLikes,omitempty"`
}

// ListUserLikesParamsListUserLikesSortDirection defines parameters for ListUserLikes.
type ListUserLikesParamsListUserLikesSortDirection string

// ListUserLikesParamsListUserLikesType defines parameters for ListUserLikes.
type ListUserLikesParamsListUserLikesType string

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = externalRef0.LoginRequest

// LogoutUserJSONRequestBody defines body for LogoutUser for application/json ContentType.
type LogoutUserJSONRequestBody = externalRef0.LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = externalRef0.RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = externalRef0.RegisterRequest

// CreateRecipeJSONRequestBody defines body for CreateRecipe for application/json ContentType.
type CreateRecipeJSONRequestBody = externalRef0.CreateRecipeRequest

// UpdateRecipeJSONRequestBody defines body for UpdateRecipe for application/json ContentType.
type UpdateRecipeJSONRequestBody = externalRef0.UpdateRecipeRequest

// UploadImageMultipartRequestBody defines body for UploadImage for multipart/form-data ContentType.
type UploadImageMultipartRequestBody UploadImageMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with username and password
	// (POST /api/v1/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /api/v1/auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// List recipes
	// (GET /api/v1/recipes)
	ListRecipes(w http.ResponseWriter, r *http.Request, params ListRecipesParams)
	// Create recipe
	// (POST /api/v1/recipes)
	CreateRecipe(w http.ResponseWriter, r *http.Request)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteRecipe(w http.ResponseWriter, r *http.Request, recipeId string)
	// Get recipe by ID
	// (GET /api/v1/recipes/{recipe_id})
	GetRecipe(w http.ResponseWriter, r *http.Request, recipeId string)
	// Update recipe
	// (PUT /api/v1/recipes/{recipe_id})
	UpdateRecipe(w http.ResponseWriter, r *http.Request, recipeId string)
	// Toggle like on a recipe
	// (POST /api/v1/recipes/{recipe_id}/like)
	ToggleRecipeLike(w http.ResponseWriter, r *http.Request, recipeId string)
	// Upload an image
	// (POST /api/v1/uploads/images)
	UploadImage(w http.ResponseWriter, r *http.Request)
	// Get image by ID
	// (GET /api/v1/uploads/images/{image_id})
	GetImage(w http.ResponseWriter, r *http.Request, imageId string)
	// Get current user profile
	// (GET /api/v1/users/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// List liked recipes
	// (GET /api/v1/users/{user_id}/likes)
	ListUserLikes(w http.ResponseWriter, r *http.Request, userId string, params ListUserLikesParams)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecipes operation middleware
func (siw *ServerInterfaceWrapper) ListRecipes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecipesParams

	// ------------- Optional query parameter "listRecipes" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "listRecipes", r.URL.Query(), &params.ListRecipes, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listRecipes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecipes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecipe operation middleware
func (siw *ServerInterfaceWrapper) CreateRecipe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecipe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRecipe operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecipe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRecipe(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecipe operation middleware
func (siw *ServerInterfaceWrapper) GetRecipe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecipe(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecipe operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecipe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecipe(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ToggleRecipeLike operation middleware
func (siw *ServerInterfaceWrapper) ToggleRecipeLike(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ToggleRecipeLike(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadImage operation middleware
func (siw *ServerInterfaceWrapper) UploadImage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadImage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "image_id" -------------
	var imageId string

	err = runtime.BindStyledParameterWithOptions("simple", "image_id", r.PathValue("image_id"), &imageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "image_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImage(w, r, imageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserLikes operation middleware
func (siw *ServerInterfaceWrapper) ListUserLikes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", r.PathValue("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserLikesParams

	// ------------- Optional query parameter "listUserLikes" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "listUserLikes", r.URL.Query(), &params.ListUserLikes, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listUserLikes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserLikes(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/login", wrapper.LoginUser)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/logout", wrapper.LogoutUser)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshToken)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes", wrapper.ListRecipes)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/recipes", wrapper.CreateRecipe)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.DeleteRecipe)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.GetRecipe)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.UpdateRecipe)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/recipes/{recipe_id}/like", wrapper.ToggleRecipeLike)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/uploads/images", wrapper.UploadImage)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/uploads/images/{image_id}", wrapper.GetImage)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/users/me", wrapper.GetCurrentUser)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/users/{user_id}/likes", wrapper.ListUserLikes)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthCheck)

	return m
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse externalRef0.AuthResponse

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser400JSONResponse externalRef0.ApiErrorResponse

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401JSONResponse externalRef0.ApiErrorResponse

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser500Response struct {
}

func (response LoginUser500Response) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type LogoutUserRequestObject struct {
	Body *LogoutUserJSONRequestBody
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser204Response struct {
}

func (response LogoutUser204Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LogoutUser400Response struct {
}

func (response LogoutUser400Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type LogoutUser401Response struct {
}

func (response LogoutUser401Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LogoutUser500Response struct {
}

func (response LogoutUser500Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse externalRef0.TokensResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken401JSONResponse externalRef0.ApiErrorResponse

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken500Response struct {
}

func (response RefreshToken500Response) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse externalRef0.AuthResponse

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser400JSONResponse externalRef0.ApiErrorResponse

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse externalRef0.ApiErrorResponse

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser422JSONResponse externalRef0.ApiErrorResponse

func (response RegisterUser422JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser500Response struct {
}

func (response RegisterUser500Response) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type ListRecipesRequestObject struct {
	Params ListRecipesParams
}

type ListRecipesResponseObject interface {
	VisitListRecipesResponse(w http.ResponseWriter) error
}

type ListRecipes200JSONResponse RecipePage

func (response ListRecipes200JSONResponse) VisitListRecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRecipes400Response struct {
}

func (response ListRecipes400Response) VisitListRecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListRecipes500Response struct {
}

func (response ListRecipes500Response) VisitListRecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type CreateRecipeRequestObject struct {
	Body *CreateRecipeJSONRequestBody
}

type CreateRecipeResponseObject interface {
	VisitCreateRecipeResponse(w http.ResponseWriter) error
}

type CreateRecipe201JSONResponse externalRef0.Recipe

func (response CreateRecipe201JSONResponse) VisitCreateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateRecipe400Response struct {
}

func (response CreateRecipe400Response) VisitCreateRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteRecipeRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type DeleteRecipeResponseObject interface {
	VisitDeleteRecipeResponse(w http.ResponseWriter) error
}

type DeleteRecipe204Response struct {
}

func (response DeleteRecipe204Response) VisitDeleteRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteRecipe400Response struct {
}

func (response DeleteRecipe400Response) VisitDeleteRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetRecipeRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type GetRecipeResponseObject interface {
	VisitGetRecipeResponse(w http.ResponseWriter) error
}

type GetRecipe200JSONResponse externalRef0.Recipe

func (response GetRecipe200JSONResponse) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRecipe403JSONResponse externalRef0.ApiErrorResponse

func (response GetRecipe403JSONResponse) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetRecipe404JSONResponse externalRef0.ApiErrorResponse

func (response GetRecipe404JSONResponse) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRecipe500Response struct {
}

func (response GetRecipe500Response) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type UpdateRecipeRequestObject struct {
	RecipeId string `json:"recipe_id"`
	Body     *UpdateRecipeJSONRequestBody
}

type UpdateRecipeResponseObject interface {
	VisitUpdateRecipeResponse(w http.ResponseWriter) error
}

type UpdateRecipe200JSONResponse externalRef0.Recipe

func (response UpdateRecipe200JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRecipe400JSONResponse externalRef0.ApiErrorResponse

func (response UpdateRecipe400JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRecipe403JSONResponse externalRef0.ApiErrorResponse

func (response UpdateRecipe403JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRecipe404JSONResponse externalRef0.ApiErrorResponse

func (response UpdateRecipe404JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLikeRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type ToggleRecipeLikeResponseObject interface {
	VisitToggleRecipeLikeResponse(w http.ResponseWriter) error
}

type ToggleRecipeLike200JSONResponse externalRef0.ToggleLikeResponse

func (response ToggleRecipeLike200JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLike401JSONResponse externalRef0.ApiErrorResponse

func (response ToggleRecipeLike401JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLike404JSONResponse externalRef0.ApiErrorResponse

func (response ToggleRecipeLike404JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLike500JSONResponse externalRef0.ApiErrorResponse

func (response ToggleRecipeLike500JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UploadImageRequestObject struct {
	Body *multipart.Reader
}

type UploadImageResponseObject interface {
	VisitUploadImageResponse(w http.ResponseWriter) error
}

type UploadImage201JSONResponse externalRef0.Image

func (response UploadImage201JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UploadImage400Response struct {
}

func (response UploadImage400Response) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UploadImage413Response struct {
}

func (response UploadImage413Response) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(413)
	return nil
}

type UploadImage500Response struct {
}

func (response UploadImage500Response) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetImageRequestObject struct {
	ImageId string `json:"image_id"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200ImageResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response GetImage200ImageResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImage404Response struct {
}

func (response GetImage404Response) VisitGetImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetImage500Response struct {
}

func (response GetImage500Response) VisitGetImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse externalRef0.CurrentUser

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401Response struct {
}

func (response GetCurrentUser401Response) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListUserLikesRequestObject struct {
	UserId string `json:"user_id"`
	Params ListUserLikesParams
}

type ListUserLikesResponseObject interface {
	VisitListUserLikesResponse(w http.ResponseWriter) error
}

type ListUserLikes200JSONResponse LikedRecipePage

func (response ListUserLikes200JSONResponse) VisitListUserLikesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListUserLikes401Response struct {
}

func (response ListUserLikes401Response) VisitListUserLikesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListUserLikes404Response struct {
}

func (response ListUserLikes404Response) VisitListUserLikesResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListUserLikes500Response struct {
}

func (response ListUserLikes500Response) VisitListUserLikesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200TextResponse string

func (response HealthCheck200TextResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login with username and password
	// (POST /api/v1/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Logout user
	// (POST /api/v1/auth/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// List recipes
	// (GET /api/v1/recipes)
	ListRecipes(ctx context.Context, request ListRecipesRequestObject) (ListRecipesResponseObject, error)
	// Create recipe
	// (POST /api/v1/recipes)
	CreateRecipe(ctx context.Context, request CreateRecipeRequestObject) (CreateRecipeResponseObject, error)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteRecipe(ctx context.Context, request DeleteRecipeRequestObject) (DeleteRecipeResponseObject, error)
	// Get recipe by ID
	// (GET /api/v1/recipes/{recipe_id})
	GetRecipe(ctx context.Context, request GetRecipeRequestObject) (GetRecipeResponseObject, error)
	// Update recipe
	// (PUT /api/v1/recipes/{recipe_id})
	UpdateRecipe(ctx context.Context, request UpdateRecipeRequestObject) (UpdateRecipeResponseObject, error)
	// Toggle like on a recipe
	// (POST /api/v1/recipes/{recipe_id}/like)
	ToggleRecipeLike(ctx context.Context, request ToggleRecipeLikeRequestObject) (ToggleRecipeLikeResponseObject, error)
	// Upload an image
	// (POST /api/v1/uploads/images)
	UploadImage(ctx context.Context, request UploadImageRequestObject) (UploadImageResponseObject, error)
	// Get image by ID
	// (GET /api/v1/uploads/images/{image_id})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// Get current user profile
	// (GET /api/v1/users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// List liked recipes
	// (GET /api/v1/users/{user_id}/likes)
	ListUserLikes(ctx context.Context, request ListUserLikesRequestObject) (ListUserLikesResponseObject, error)
	// Health check
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(w http.ResponseWriter, r *http.Request) {
	var request LogoutUserRequestObject

	var body LogoutUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx, request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		if err := validResponse.VisitLogoutUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRecipes operation middleware
func (sh *strictHandler) ListRecipes(w http.ResponseWriter, r *http.Request, params ListRecipesParams) {
	var request ListRecipesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRecipes(ctx, request.(ListRecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRecipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRecipesResponseObject); ok {
		if err := validResponse.VisitListRecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRecipe operation middleware
func (sh *strictHandler) CreateRecipe(w http.ResponseWriter, r *http.Request) {
	var request CreateRecipeRequestObject

	var body CreateRecipeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRecipe(ctx, request.(CreateRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRecipeResponseObject); ok {
		if err := validResponse.VisitCreateRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteRecipe operation middleware
func (sh *strictHandler) DeleteRecipe(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request DeleteRecipeRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRecipe(ctx, request.(DeleteRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRecipeResponseObject); ok {
		if err := validResponse.VisitDeleteRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecipe operation middleware
func (sh *strictHandler) GetRecipe(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request GetRecipeRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecipe(ctx, request.(GetRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecipeResponseObject); ok {
		if err := validResponse.VisitGetRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRecipe operation middleware
func (sh *strictHandler) UpdateRecipe(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request UpdateRecipeRequestObject

	request.RecipeId = recipeId

	var body UpdateRecipeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRecipe(ctx, request.(UpdateRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRecipeResponseObject); ok {
		if err := validResponse.VisitUpdateRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ToggleRecipeLike operation middleware
func (sh *strictHandler) ToggleRecipeLike(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request ToggleRecipeLikeRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ToggleRecipeLike(ctx, request.(ToggleRecipeLikeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ToggleRecipeLike")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ToggleRecipeLikeResponseObject); ok {
		if err := validResponse.VisitToggleRecipeLikeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadImage operation middleware
func (sh *strictHandler) UploadImage(w http.ResponseWriter, r *http.Request) {
	var request UploadImageRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadImage(ctx, request.(UploadImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadImageResponseObject); ok {
		if err := validResponse.VisitUploadImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(w http.ResponseWriter, r *http.Request, imageId string) {
	var request GetImageRequestObject

	request.ImageId = imageId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx, request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		if err := validResponse.VisitGetImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUserLikes operation middleware
func (sh *strictHandler) ListUserLikes(w http.ResponseWriter, r *http.Request, userId string, params ListUserLikesParams) {
	var request ListUserLikesRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUserLikes(ctx, request.(ListUserLikesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUserLikes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUserLikesResponseObject); ok {
		if err := validResponse.VisitListUserLikesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc3XPbOJL/V1C8e7i7Yiw7yaV2/ZaP2YxrPBNXJtl9SLlUENmSMAYBDgDK1rr0v2+h",
	"wQ+QBClasWNnKi+JTIKNRn/8utEN8jZKZJZLAcLo6PQ2yqmiGRhQ+FcmU+B6fs60+QgJy0Ff2Pt4D25y",
	"LlOITo0qII6YiE6jPwtQ2yiOBM0gOo1481wURzpZQ0bto5TzD8vo9Mtt9N8KltFp9F+zhouZG6dn5eQX",
	"dMUENUyKcu5dfBvlSuagDANkhRZmLdVZan+noBPFcjs+Oo3+wbgBRRZb4sZEcWS2ueVNG8XEKtrF0ULB",
	"9a9g1hKfn8DRm+aBXRylbLlkScHNduLj75oHdnEpsh7jvwNVyZooJz27AMMMByIV8QcGlqOlMvOUKUgc",
	"qR5lqQxp7scRiCKLTr9EVCdRjIOjyyG6SwY8KGbgKTGS2EFksY0JHK2OSKKAGkjn1MSO/Zh40mpmbsbZ",
	"BdmBAQ529RW5+AMSE+0uLVdmy+21pVSZ5dKz2M8a1Dm7OsBm6ycf1GrvpihrApxdVVKaqDR3oUv50zYH",
	"IpeOHlGgZaES8Kg6swsrQcGfBVOQ2nF493KCYnaVIHHlVrapA4YLuoJDhAsBgTIDWfvHBFoeL43AIqoU",
	"3Q7Z3BPh/G5Mlw+9ztlPSkn1EXQuhcYVtHkBe7tvMz8XGRXPFNCULjgQHEUy0NquaJ+dOJp9Q2nYKsx6",
	"mCWaJKD13MgrCPnJWirzjLMNWAi6AkGWUiHegzAsoYaJFbHcgDY6hJgKlgr0eoj+J6RZaCRP5MJQJggl",
	"Aq6JY8zNGqJcaFATtWkxp5ZAV35tDuO2QMppRqT7phXh2qt7K5dLAGKDoJVT5oY1ULB5dRzF0VKBSNbz",
	"XIG2IqSgZPXbLgNu7A/J07mlY5++wdtyntFkzYS1kExe0XkuTRCnPEZ/N5AHlMzEigPRBnKLXGbdsJwr",
	"mThW2lbTItCl9w4MZRxSwoQ2qkCI1Wg4lrSdJqTPtFCI6XMNiRRpf5roA/6gnFRDK26RcyZI9WQciYJz",
	"60tVNCpnY8LACpSdjgX09VmwP4uKXGotfMnA5jUWaKlxBF69jIL0MrqCeYjq2buKzyLnkqZWMHbwEXlL",
	"BVkABgluPWzDKI7D2+VoAiLNJRPmaHhZjRClSiEAMB/s5a607O8yGIUW5HKFMCJUCdNyRKMdN2PW8B17",
	"/Twk6FXWWC/o1goBgSpNmdP/hWeKS8o1xD8M+ocB7jPAybb3tlAKBCaqd85B2pHGyw3etXYyHfOq7xEO",
	"G+DVsmrZVPECqLbZdAYpK7IojtZUpWOQf5aVeVQH5lpW0HOFEWR0dtGCxr1ePyJpPz/sJSZ1Qn562+Bv",
	"Sg08MyyDcK5RUZqc4V0o2DC47vHt7QZ6+XpgGRkzuBVxglvSgpvo9PlxF5d+K7KFcwPMRUkOiuROBX6E",
	"efE86A/VbHLFxEeXcu3FxbZIc6r1tVQh/WpkpbztseNdy5g4B7Ey6+j0ZCAfc/u8AeOpB+wh1VGFx0FN",
	"YUwZciUL48mnLYJePjo+eXv4yLQXQU97DwIUS6yS7Y7VbQgdOMRD25Q2BbvZbgxGWtBkujKa6pneNiWO",
	"8nqPPNEfmk31r2Bo35FxqhbdPdLoO8RJ1x/sMCLQKUIukDHBMot8JyPu0OG7p/DEofk8DyqoxHoU6MGc",
	"oGzmiSyE6c/Q9Xnp4l7iTTw643FoRk710IrOqf7K5Qi4GSL+G9x8FfGQUZWCi9ua8tnw1ztudO2yUCCk",
	"ZMxMrl3UoO7cCaY7Umn7gWpBzWwT9Ua3jHUKECrK7kv2LKZfr2VVKgzmW16pFqjQwwzZu26jXuW9Nam9",
	"SaFdzTw7vAzs1TD7FQSWgTY0y8n1GvycklxTXS3dt9PRFGLaNsC73MvV+iS/roY9ko2V6xxLx57KtoDp",
	"OaZUfS7+tQazBtUCRbTcNdVlERVDXlfACyk5UIFoyK5gEH8/SUN5CVdVXVZPS7jyYsFZEhCcSFlCDWhr",
	"cjXzlTY0cc/xLdkwzRYcjoJcK2lBDRP+qSmrfeIcH8AiMOR6YKcFKeFl4lAhiRse36kKWpeMAgnGwO7M",
	"4ZrbngWrdnl6oCvbGEDKxyf6c6gE0UBntYa217fRquW+lcxry4jb3RVvbW2j9Oz/cl9ImFrxaAeEJwze",
	"TxBSnwQk+uhSJsjBYtZd0eZ7B5vKAe4Lc7pttcN8fr/flpWEwA5utTbXYP+ttKYgV6BBGFf0sz5pJagJ",
	"FSlJqEr1t8n4vp+07EcO9Z3mUF8LPPfh8oNxf8TrB8J3y+hHMQHrRoeV6fb0TEvaZT/W9UxtBC3s4gmX",
	"KyaIVETBimnj+gp7RTS5zvURqYI6bGV0Qw1VUz3JjX44h1owOdReQO9ZMLlSNF9vpxCDjDI+UFjFe4Sm",
	"adnWrf3GPRRKDqZVao/Ir4U2Vix/e/biOUnWVNHEgNJHAzXcw6u2zVSvnp288qaKCQfjfjiEcGGsECko",
	"nUgFmkjBt0f7DzKUwrhjwdfDi6H8F0HI9Va8bgq3Iblup8zbfzbXU6quLDrY/0Z6LZ/kasXhnF2Bf9bi",
	"Dr4xgO2fVAGEOczF2EnTFNKYIA17Q0EmN5DeHdU/u+0KMYjuOJRUgLcX2UP9kg5sjugMj33ov9yhlI5Q",
	"OidJJmNsq4nYl81fF0NH8jQkNp6l3aUBNSFhGMEeuyGCpFDMbH/HIzqomDdAFajXhVnjCUS8Yd0RLzdz",
	"ro3BgspbKa8YVMPxuGSCl5rzkt2jSdV+KGe/wDbaWT6YWAYUgJjIyOs8J68vzuqMx78RxdEGlHbjj4+O",
	"j06wfZ+DoDmLTqMXR8dHx4jGZo3Lm9GczTYnM+tnM8wy0DalDkDL68YXQRNabkyYWdc6wBhRIT3+ocAU",
	"SujKxdwlL9PBmGYdATOas9RurSwX2Kd3+gNt3sgU9wiJFAYc6tE854gKUsz+0K4K0Zw8ndIK8Duuu7ax",
	"WEvGC85dUVLPj4/vm4XWGT5kobPJxKxPFyi7ZYGp88sHYKN7wjHAyhuaVuDruDh5DC7OxIZyltqdJoIG",
	"5dpy8/9OJt2xxholJxrUxqZreKLS9/Lo9MtlHOkiy6ja1uIeNmjrcXSlMQhYB6+rPZeWateTZGGGXalc",
	"CDqShepcyQ1LoeMcMYHlEhLDNsC3dg+wsjGwrgnIwgS9Rxbmm7iP15HflQ7U8peXgbKJXK0gtZx7Zs23",
	"nmFPMbtuHHC7QPZvSA+xBl//lrHCya6l6r6GS0WNqFjrAmGym2GQQls1UuJsuaXxvj7LfeGnOt14MI12",
	"drdBld479nRyxoDPu7ytlBKkAbt5VCiSisBNbsNGW5P3iEtVaaCbpk7EIlVu7odN9S1WPypbRWyhCab7",
	"h8bwqqDw8DjULV1MiuQn3zqS4/6+UkTQiJ9GVP/7Y3DxuQq2si6qcAU03RJDS096+fz5Y3D2TxekmRSV",
	"m96jUztj8Jxumk+XL7hZHlZgQoXE0lu982lVJ6d6OQ5zHFmdU17iK3+6eecvxpZP+WaD/wZajM6vpbKb",
	"8UDu0Xp70X8xcuCcbTNkNvji5O7yAaOQ92JSQP0XQwKcmq8cnorY+VQtysosqiuXu3gSlCehc0d1t9ir",
	"rUCKFthXqaP3sWoxPCiQ+43yx4Hx6gWxvimUrYmqxTVJ/y2NOkF6zZqeSvs+Prt1P+Ys3bm5OJhAJeQC",
	"VEbtgviWuDHWANyzR+SD4Nta31KRhIpylL3KFJHXohrc0/87HFjrv+PTWN/IKWJVXd0oOY66+vPfDO1W",
	"ai6nbB4cL4cI3z05Jvx4H5hq9/ZJ6UKLLWFGk7N3fYm9B/MI4jr+1q7gtPDiMaLyb9IQyrm8hpT8j7B/",
	"oGH/r2Pp5WOwVMKDZWYpC/F1+9D3YDw7O3s3FACKwfK/TdIJ3DBtGtgPA4E73TQBCBzhb2PZTynGfHPH",
	"qk/DPaFtwQ83H3LzluM6Hzk8xs84u4KR+nua2kiEPUO2RC6wQxeX3UJtr1ZbJ7zTd2PX0HTrOLezfddB",
	"KtCeDZXRrcAMDk0fsWLUrVM+vVD17Wto+4OhU7EzeinqtNbzLnduqeVbruepZ9gB1cMe5d6ZxGjpmqVL",
	"xqFV83JZHl76/PE8FBYthbPylcvh0JUV3LCcKjNbSpU9S6l7q6kRabsdbPlovSK5YILiR1fGe5z4XKC1",
	"+RibKSeUkNq9vvRwLWw8JJ28CH66yPq5JJwq/GjI4SmYU2ttF561laY1Zm+z2+po4W5/laZleePbisrK",
	"9gN2fbTxfvEayc7+r20J+010wADQVhscDA25v3zaCbmbToeVqbEeBXt1VzbuUHPlCY3ynCbfTiquvAfj",
	"v5b+8PHSny2gl7f+KdNyZRPbbj2BJyFanuStkENyv7X/1cnQ15U53SHZhdv06BwStmSVMsiFYpsmW9OE",
	"KsAjbdWJe2JkuS1y6wyXO/0PX+33y3Jtd3LL+C6l0+4XvB40Cet+lGpSBbX6gpZXR53Q0w1iBDZV7gci",
	"sN7aZq1rq3Er0VgD5e6Mz16IqDzBPUK0oabQ9UcuQG1YEthv/4yj364hudoPDAZuzCznlHW0Bzc0y/GI",
	"0IdfpgDzh186cnFckKRko5JI05dodzjax6W+XFrj9U9Efbm0BllSGTj9nVFBV5BB2XxMmU7kpvXBucZ4",
	"bkcyiyqNUww2lHs+WGJ+/2mvSecUEbeOH9rsU1RnExsuG8rYtBkg6/dTq5jR0IgJEwkvUvctG4dLOBLl",
	"TDBbbIFIiH3c5rhDupgt0/KLNlJ4Nl1/s+8qKMCfylOC1nKpIalE/yrBqiONhlppDrvL3X8CAAD//7gx",
	"J9gdUwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
