//go:build go1.22

// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/nikpivkin/roasti-app-backend/internal/api/models"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for ListRecipesParamsListRecipesSortDirection.
const (
	Asc  ListRecipesParamsListRecipesSortDirection = "asc"
	Desc ListRecipesParamsListRecipesSortDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListRecipesParamsListRecipesSortDirection enum.
func (e ListRecipesParamsListRecipesSortDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for ListRecipesParamsListRecipesSortField.
const (
	CreatedAt ListRecipesParamsListRecipesSortField = "created_at"
	Title     ListRecipesParamsListRecipesSortField = "title"
)

// Valid indicates whether the value is a known member of the ListRecipesParamsListRecipesSortField enum.
func (e ListRecipesParamsListRecipesSortField) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// RecipePage defines model for RecipePage.
type RecipePage struct {
	Items      []externalRef0.Recipe       `json:"items"`
	Pagination externalRef0.PaginationMeta `json:"pagination"`
}

// ListRecipesParams defines parameters for ListRecipes.
type ListRecipesParams struct {
	ListRecipes *externalRef0.ListRecipesParams `form:"listRecipes,omitempty" json:"listRecipes,omitempty"`
}

// ListRecipesParamsListRecipesSortDirection defines parameters for ListRecipes.
type ListRecipesParamsListRecipesSortDirection string

// ListRecipesParamsListRecipesSortField defines parameters for ListRecipes.
type ListRecipesParamsListRecipesSortField string

// UploadImageMultipartBody defines parameters for UploadImage.
type UploadImageMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = externalRef0.LoginRequest

// LogoutUserJSONRequestBody defines body for LogoutUser for application/json ContentType.
type LogoutUserJSONRequestBody = externalRef0.LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = externalRef0.RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = externalRef0.RegisterRequest

// CreateRecipeJSONRequestBody defines body for CreateRecipe for application/json ContentType.
type CreateRecipeJSONRequestBody = externalRef0.CreateRecipeRequest

// UpdateRecipeJSONRequestBody defines body for UpdateRecipe for application/json ContentType.
type UpdateRecipeJSONRequestBody = externalRef0.UpdateRecipeRequest

// UploadImageMultipartRequestBody defines body for UploadImage for multipart/form-data ContentType.
type UploadImageMultipartRequestBody UploadImageMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with username and password
	// (POST /api/v1/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /api/v1/auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Get current user profile
	// (GET /api/v1/profiles/me)
	GetMyProfile(w http.ResponseWriter, r *http.Request)
	// List recipes
	// (GET /api/v1/recipes)
	ListRecipes(w http.ResponseWriter, r *http.Request, params ListRecipesParams)
	// Create recipe
	// (POST /api/v1/recipes)
	CreateRecipe(w http.ResponseWriter, r *http.Request)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteRecipe(w http.ResponseWriter, r *http.Request, recipeId string)
	// Get recipe by ID
	// (GET /api/v1/recipes/{recipe_id})
	GetRecipe(w http.ResponseWriter, r *http.Request, recipeId string)
	// Update recipe
	// (PUT /api/v1/recipes/{recipe_id})
	UpdateRecipe(w http.ResponseWriter, r *http.Request, recipeId string)
	// Toggle like on a recipe
	// (POST /api/v1/recipes/{recipe_id}/like)
	ToggleRecipeLike(w http.ResponseWriter, r *http.Request, recipeId string)
	// Upload an image
	// (POST /api/v1/uploads/images)
	UploadImage(w http.ResponseWriter, r *http.Request)
	// Get image by ID
	// (GET /api/v1/uploads/images/{image_id})
	GetImage(w http.ResponseWriter, r *http.Request, imageId string)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMyProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecipes operation middleware
func (siw *ServerInterfaceWrapper) ListRecipes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecipesParams

	// ------------- Optional query parameter "listRecipes" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "listRecipes", r.URL.Query(), &params.ListRecipes, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listRecipes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecipes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecipe operation middleware
func (siw *ServerInterfaceWrapper) CreateRecipe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecipe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRecipe operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecipe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRecipe(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecipe operation middleware
func (siw *ServerInterfaceWrapper) GetRecipe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecipe(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecipe operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecipe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecipe(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ToggleRecipeLike operation middleware
func (siw *ServerInterfaceWrapper) ToggleRecipeLike(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ToggleRecipeLike(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadImage operation middleware
func (siw *ServerInterfaceWrapper) UploadImage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadImage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "image_id" -------------
	var imageId string

	err = runtime.BindStyledParameterWithOptions("simple", "image_id", r.PathValue("image_id"), &imageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "image_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImage(w, r, imageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/login", wrapper.LoginUser)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/logout", wrapper.LogoutUser)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshToken)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/profiles/me", wrapper.GetMyProfile)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes", wrapper.ListRecipes)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/recipes", wrapper.CreateRecipe)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.DeleteRecipe)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.GetRecipe)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.UpdateRecipe)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/recipes/{recipe_id}/like", wrapper.ToggleRecipeLike)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/uploads/images", wrapper.UploadImage)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/uploads/images/{image_id}", wrapper.GetImage)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthCheck)

	return m
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse externalRef0.AuthResponse

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser400JSONResponse externalRef0.ApiErrorResponse

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401JSONResponse externalRef0.ApiErrorResponse

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser500Response struct {
}

func (response LoginUser500Response) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type LogoutUserRequestObject struct {
	Body *LogoutUserJSONRequestBody
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser204Response struct {
}

func (response LogoutUser204Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LogoutUser400Response struct {
}

func (response LogoutUser400Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type LogoutUser401Response struct {
}

func (response LogoutUser401Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LogoutUser500Response struct {
}

func (response LogoutUser500Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse externalRef0.TokensResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken401JSONResponse externalRef0.ApiErrorResponse

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken500Response struct {
}

func (response RefreshToken500Response) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse externalRef0.AuthResponse

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser400JSONResponse externalRef0.ApiErrorResponse

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse externalRef0.ApiErrorResponse

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser422JSONResponse externalRef0.ApiErrorResponse

func (response RegisterUser422JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser500Response struct {
}

func (response RegisterUser500Response) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetMyProfileRequestObject struct {
}

type GetMyProfileResponseObject interface {
	VisitGetMyProfileResponse(w http.ResponseWriter) error
}

type GetMyProfile200JSONResponse externalRef0.MyProfile

func (response GetMyProfile200JSONResponse) VisitGetMyProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMyProfile401Response struct {
}

func (response GetMyProfile401Response) VisitGetMyProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListRecipesRequestObject struct {
	Params ListRecipesParams
}

type ListRecipesResponseObject interface {
	VisitListRecipesResponse(w http.ResponseWriter) error
}

type ListRecipes200JSONResponse RecipePage

func (response ListRecipes200JSONResponse) VisitListRecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRecipes400Response struct {
}

func (response ListRecipes400Response) VisitListRecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListRecipes500Response struct {
}

func (response ListRecipes500Response) VisitListRecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type CreateRecipeRequestObject struct {
	Body *CreateRecipeJSONRequestBody
}

type CreateRecipeResponseObject interface {
	VisitCreateRecipeResponse(w http.ResponseWriter) error
}

type CreateRecipe201JSONResponse externalRef0.Recipe

func (response CreateRecipe201JSONResponse) VisitCreateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateRecipe400Response struct {
}

func (response CreateRecipe400Response) VisitCreateRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteRecipeRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type DeleteRecipeResponseObject interface {
	VisitDeleteRecipeResponse(w http.ResponseWriter) error
}

type DeleteRecipe204Response struct {
}

func (response DeleteRecipe204Response) VisitDeleteRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteRecipe400Response struct {
}

func (response DeleteRecipe400Response) VisitDeleteRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetRecipeRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type GetRecipeResponseObject interface {
	VisitGetRecipeResponse(w http.ResponseWriter) error
}

type GetRecipe200JSONResponse externalRef0.Recipe

func (response GetRecipe200JSONResponse) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRecipe403JSONResponse externalRef0.ApiErrorResponse

func (response GetRecipe403JSONResponse) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetRecipe404JSONResponse externalRef0.ApiErrorResponse

func (response GetRecipe404JSONResponse) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRecipe500Response struct {
}

func (response GetRecipe500Response) VisitGetRecipeResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type UpdateRecipeRequestObject struct {
	RecipeId string `json:"recipe_id"`
	Body     *UpdateRecipeJSONRequestBody
}

type UpdateRecipeResponseObject interface {
	VisitUpdateRecipeResponse(w http.ResponseWriter) error
}

type UpdateRecipe200JSONResponse externalRef0.Recipe

func (response UpdateRecipe200JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRecipe400JSONResponse externalRef0.ApiErrorResponse

func (response UpdateRecipe400JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRecipe403JSONResponse externalRef0.ApiErrorResponse

func (response UpdateRecipe403JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRecipe404JSONResponse externalRef0.ApiErrorResponse

func (response UpdateRecipe404JSONResponse) VisitUpdateRecipeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLikeRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type ToggleRecipeLikeResponseObject interface {
	VisitToggleRecipeLikeResponse(w http.ResponseWriter) error
}

type ToggleRecipeLike200JSONResponse externalRef0.ToggleLikeResponse

func (response ToggleRecipeLike200JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLike401JSONResponse externalRef0.ApiErrorResponse

func (response ToggleRecipeLike401JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLike404JSONResponse externalRef0.ApiErrorResponse

func (response ToggleRecipeLike404JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ToggleRecipeLike500JSONResponse externalRef0.ApiErrorResponse

func (response ToggleRecipeLike500JSONResponse) VisitToggleRecipeLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UploadImageRequestObject struct {
	Body *multipart.Reader
}

type UploadImageResponseObject interface {
	VisitUploadImageResponse(w http.ResponseWriter) error
}

type UploadImage201JSONResponse externalRef0.Image

func (response UploadImage201JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UploadImage400Response struct {
}

func (response UploadImage400Response) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UploadImage413Response struct {
}

func (response UploadImage413Response) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(413)
	return nil
}

type UploadImage500Response struct {
}

func (response UploadImage500Response) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetImageRequestObject struct {
	ImageId string `json:"image_id"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200ImageResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response GetImage200ImageResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImage404Response struct {
}

func (response GetImage404Response) VisitGetImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetImage500Response struct {
}

func (response GetImage500Response) VisitGetImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200TextResponse string

func (response HealthCheck200TextResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login with username and password
	// (POST /api/v1/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Logout user
	// (POST /api/v1/auth/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Register a new user
	// (POST /api/v1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Get current user profile
	// (GET /api/v1/profiles/me)
	GetMyProfile(ctx context.Context, request GetMyProfileRequestObject) (GetMyProfileResponseObject, error)
	// List recipes
	// (GET /api/v1/recipes)
	ListRecipes(ctx context.Context, request ListRecipesRequestObject) (ListRecipesResponseObject, error)
	// Create recipe
	// (POST /api/v1/recipes)
	CreateRecipe(ctx context.Context, request CreateRecipeRequestObject) (CreateRecipeResponseObject, error)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteRecipe(ctx context.Context, request DeleteRecipeRequestObject) (DeleteRecipeResponseObject, error)
	// Get recipe by ID
	// (GET /api/v1/recipes/{recipe_id})
	GetRecipe(ctx context.Context, request GetRecipeRequestObject) (GetRecipeResponseObject, error)
	// Update recipe
	// (PUT /api/v1/recipes/{recipe_id})
	UpdateRecipe(ctx context.Context, request UpdateRecipeRequestObject) (UpdateRecipeResponseObject, error)
	// Toggle like on a recipe
	// (POST /api/v1/recipes/{recipe_id}/like)
	ToggleRecipeLike(ctx context.Context, request ToggleRecipeLikeRequestObject) (ToggleRecipeLikeResponseObject, error)
	// Upload an image
	// (POST /api/v1/uploads/images)
	UploadImage(ctx context.Context, request UploadImageRequestObject) (UploadImageResponseObject, error)
	// Get image by ID
	// (GET /api/v1/uploads/images/{image_id})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// Health check
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(w http.ResponseWriter, r *http.Request) {
	var request LogoutUserRequestObject

	var body LogoutUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx, request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		if err := validResponse.VisitLogoutUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyProfile operation middleware
func (sh *strictHandler) GetMyProfile(w http.ResponseWriter, r *http.Request) {
	var request GetMyProfileRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyProfile(ctx, request.(GetMyProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyProfileResponseObject); ok {
		if err := validResponse.VisitGetMyProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRecipes operation middleware
func (sh *strictHandler) ListRecipes(w http.ResponseWriter, r *http.Request, params ListRecipesParams) {
	var request ListRecipesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRecipes(ctx, request.(ListRecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRecipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRecipesResponseObject); ok {
		if err := validResponse.VisitListRecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRecipe operation middleware
func (sh *strictHandler) CreateRecipe(w http.ResponseWriter, r *http.Request) {
	var request CreateRecipeRequestObject

	var body CreateRecipeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRecipe(ctx, request.(CreateRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRecipeResponseObject); ok {
		if err := validResponse.VisitCreateRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteRecipe operation middleware
func (sh *strictHandler) DeleteRecipe(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request DeleteRecipeRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRecipe(ctx, request.(DeleteRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRecipeResponseObject); ok {
		if err := validResponse.VisitDeleteRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecipe operation middleware
func (sh *strictHandler) GetRecipe(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request GetRecipeRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecipe(ctx, request.(GetRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecipeResponseObject); ok {
		if err := validResponse.VisitGetRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRecipe operation middleware
func (sh *strictHandler) UpdateRecipe(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request UpdateRecipeRequestObject

	request.RecipeId = recipeId

	var body UpdateRecipeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRecipe(ctx, request.(UpdateRecipeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRecipe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRecipeResponseObject); ok {
		if err := validResponse.VisitUpdateRecipeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ToggleRecipeLike operation middleware
func (sh *strictHandler) ToggleRecipeLike(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request ToggleRecipeLikeRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ToggleRecipeLike(ctx, request.(ToggleRecipeLikeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ToggleRecipeLike")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ToggleRecipeLikeResponseObject); ok {
		if err := validResponse.VisitToggleRecipeLikeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadImage operation middleware
func (sh *strictHandler) UploadImage(w http.ResponseWriter, r *http.Request) {
	var request UploadImageRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadImage(ctx, request.(UploadImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadImageResponseObject); ok {
		if err := validResponse.VisitUploadImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(w http.ResponseWriter, r *http.Request, imageId string) {
	var request GetImageRequestObject

	request.ImageId = imageId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx, request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		if err := validResponse.VisitGetImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW3PbOJb+KyjuPuxuMZadZFMzekvsnm5XO21XOpl5SLlUEHEkoQ0CbACUrXHpv0/h",
	"gHeCEq3YsburnyKTuBycy3duYO6jRKWZkiCtiab3UUY1TcGCxr9SxUCY2QU39hMkPANz5d7jO7jLhGIQ",
	"Ta3OIY64jKbR7znoTRRHkqYQTSNRz4viyCQrSKmbSoW4XETTr/fRf2tYRNPovyY1FRM/zkyKza/okktq",
	"uZLF3tv4Psq0ykBbDkgKze1K6XPmfjMwieaZGx9No39wYUGT+Yb4MVEc2U3maDNWc7mMtnE013D7EexK",
	"4fwRFH2oJ2zjiPHFgie5sJuR08/qCds4MkrbGeMaEk9y9wS/Km1J/T6OQOZpNP0aUZNEMQ6OrgOnwnUX",
	"HESQKyAYsYq4QWS+iQkcLY9IooFaYDNqY2K5FRCTxuHqnetxjp1uYICCbfVEzX+DxEbba0eV3Qj3bKF0",
	"imMK3jgavaZc0SUcoiMQ0AtuIW3/GLGWJyOq6ada083QgYpJ7zP+g9ZKfwKTKWnwBG1awL3ui+KnPKXy",
	"lQbK6FwAwVEkBWPciUJM1fB7zjUwJwi/5nWPsJqs3K6GSaJJAsbMrLqBkOKtlLavBF+DU5UbkGShNJoR",
	"SMsTarlcEkcNGGtCdqVhocGshtb/jGvmBpcnam4pl4QSCbfEE+Z3Da2cG9AjpfnFQC2ULv/aFMZthhTb",
	"7ODuhxZwtE93qhYLAOKwxfEp9cNqG1q/O47iaKFBJqtZpsE4FlLQqvztjgF37ocSbObWcbPv8LWapTRZ",
	"cek0JFU3dJYpGwSBBqG/WsgCQuZyKYAYCxlRC2JXNcmZVoknpa01rQW6652BpVwAI1waq3PELIOK45Z2",
	"24TkyXKNAD8zkCjJ+ttEl/iDClIOLalFyrkk5cw4krkQzpZKx1TsxqWFJWi3HQ/I64vkv+flcsxp+IKD",
	"cxcOqaj1C7x7GwXXS+kSZqFVz89KOvNMKMocY9zgI3JKJZkD0WCUcBa25hTH4etiNAHJMsWlPRo+Vs1E",
	"pRkEAObSPe5yy/3WHudCB/KYHkYE7xmaC+6FKe4U35PX9xdBq3LKekU3jgkIVIxxL/+rhiouqDAQ/6XQ",
	"fyngPgUcrXtnrViuownVOyJgDaKkoDpGCe1AjYuWUmA8T6M4WlHNdqHzeVqEPB1Eagmsp7U7QMyLsIVi",
	"ew10B1MueMotxt5+xwXNhY2mr4+7tvdLns69qDHeIhloknnamyj65nVQ5uVuasnlJx9W7LX9Nksyasyt",
	"0iHGGCSleN0gp/Es5fIC5NKuounJQMzh05oBrlcD9izV4X2DgmqFXcJQS5XbBn/aLOjFXLs3bw/fse3H",
	"zZVWCy4eHpq3A7BGyHwV1PofQYLmidMbl/UBcwjlJ8dD0X17BZes1jqoHNZwU+phOacX3cdRVuWZI0PL",
	"OjH9CJb2jQq3aq27g8GOG30bO+mamBtGJNpZyKpSLnnqUOhkh4V16O7pUJJrDdLOsqCATv1bZOjBlCBv",
	"ZonKpe3v0IUR5d1F0th4547HoR0FNUMnuqDmG48j4W5o8V/g7psWDylVwbi4LakmGc3z7la6dmmlpwvC",
	"Yf9Ie2j4CW9OMN6QCt0PJNkVsUVevi/TqtxxqES0L0ZybuJ2pcpKSDBMaRSOgEozTJB76/PbMlysltob",
	"S7nTzNLDi1KNEk0/8eYpGEvTjNyuoBmKkVtqyqM39ZRRC68sT4NMGBc9Nx734qb+kt9WUdsRGRXn3BUa",
	"vZRompuZ4DcQoOJfK7Ar0C1QRM1dUUNwjnd5XQbPlRJAJaIhv4FB/P2sLBUFXLnz4uBxMVyWzwVPAoyT",
	"jCfUgnEqVxFfSsMQP09syJobPhdwFKRaKwdqGHyPreW5GRc4AYuPkJmBBAUYEUXgUCKJHx4/qHhYVVoC",
	"AcZAUuNxzWc1wWJXxg40ZecDSDF9pD2HMvcaOssztK2+jVYt8y15XmlG3C4eN87WVsqG/l/vcwljCwVt",
	"h/CCwfsFQuqLgMQmuhQBcrAG9FC0+aODTWkAj4U5HRA40OZ32i2mnYdl+XvaCsXaRcvCtxWcteTubESo",
	"JZdEaaJhyY31pbe9HBidJn/CVV3Ce8jJ6JpaqseamR/9dNY252qoAofRxpyrpabZajNmMUgpFwN1GXxH",
	"KGNF56PyU35SCAjGFXqOyMfcWMeWv71685okK6ppYkGbo4ES0OFFn3qrd69O3jW2iokA63/4iMoQKhnJ",
	"JQNtEqXB5bdic7S/11cw44H1ogYoDfk6RDpf02xUMQVfrmxVxpy1/6yfM6pvnP27f3bUOD+r5VLABb+B",
	"ZjvyAbYxEAt/1jkQ7mNUjHkoY8Bigmu4FxpStQb28Cj4iw9NiMVoGIeSMjbZGwl3ZOeJb2+4Q2bYGTV/",
	"ur5thymdZutojG0VFPu8+fNi6I68FhfbndU+pH49IinYgT0u+IEk19xufsUuNgrmA1AN+n1uV+4vjGTQ",
	"HPFxvefKWkyeTpW64VAOx8tFCT6qbxd1u/dl7JPxn2ETbR0dXC4CAkBM5OR9lpH3V+dVVtN8EcXRGrTx",
	"44+Pjo9OsMOVgaQZj6bRm6Pjo2NEY7vC401oxifrk4mzswlGGaibygSg5X1ti2AILcpO3K4qGaCPKJEe",
	"/9Bgcy1NaWL+USPSQZ/mDAEjmnMWTSPspDhribz8wNgPimECkChpwaMezTKBqKDk5DfjM476ptaYsl+z",
	"YbNtK4vTZHzgzRU59fr4+LFJaF1zQRI6FV6M+kyOvFvkGJ+/fQIyupeAAqR8oKwEX0/FyXNQcS7XVHBG",
	"Eg0IGlQYR83/e550x1qnlIIY0GsXruGlo6aVR9Ov13Fk8jSlelOxe1ihncXRpUEn4Ay8yuyu3apdS1K5",
	"HTal4iBoSA6qM63WnEHHOGICiwUklq9BbFwOsHQ+sKr4qtwGrUfl9ruYT6Ohty0MqGUvbwM9C7VcAnOU",
	"N9RabBqKPUbtun7AV3r4v4Edog1N+TvCcs+7lqj7Ei4EtUPExuQIk90Ig+TGiZESr8stifflWeSFn6tw",
	"48kk2slugyJ9dOzpxIwBm/dxW8ElYAG9eVYoUprAXebcRluSj4hLZWmgG6aOxCJdJPfDqnqKtc1SVxFb",
	"aILh/qE+vCwoPD0OdUsXozz5yff25Jjfl4IIKvHL8Op/fw4qvpTOVlVFFaGBsg2xtLCkt69fPwdl//RO",
	"mitZmukjGrVXhobRjbPpzF9oMROfEy3BhoqJ3mKL0MKNL3PIovMmNs3UGhgS0LfjH8HWV2ie3hvUewWE",
	"cdrsGWbluFFBQcvN/wi23X/MqvOV7C953Oa8Lj4J2cd12rgFVNbLi7k+ulTlJcoFfuZh6u88YiysF9eu",
	"m58xxAi7RmnL5TIQ9bW+WGl+DDNw26keMhn8WGZ7/YQSb3w1EZD11RADx0aKhweBbj9dsbLUiPLJ9TYe",
	"5UST0O2Oqic3xvT8ep/K1tiTutBmO/J5HGj59UpfFYqeT3m/Y5T8WxL1jGw0GXsi7dv45N7/mHG29XsJ",
	"sIEa1BXolEqPp36MUwA/94hcSrGp5K00SagsRrmnXBN1K8vBPfmf4cBK/h2bxspSRtFLVHWlguKoK7/m",
	"N2zdGtn1mLTN03II8/3MXcyP94Gp8VfjCxOabwi3hpyfBZ3VM7Dr+HubgpfCm+eIh35RllAh1C0w8j/S",
	"/YGK/b+epLfPQVIBD46Yhcrlt1UAXGhQ69n52ZADyAcbLy49InDHja1hPwwE/g7JCCDwC38fzX5JPua7",
	"G1Z15+gFJWR/mfmQmbcM19vI4T5+IvgN7Oh8MOY8EXZr+QKpwN5oXPRpjXtaJq34pm/GvpXsz3HhdvtD",
	"O6lAYzzUwHAMsziUPWOtrlshfnmu6vtXL/c7Qy9ir/RKVmFtw7r8DduWbflus5lg79kMW5T/Sgy9pW9T",
	"Y42iWW30UR4++vLpIuQW3QrnxUdmw64rzYXlGdV2slA6fcWo/3akZmm7EV9+LFTdlZhzSfE/h9jdXcZ5",
	"gabycyRTnikhsTduBAxXIXe7pJM3wf+uwtm5IoJq/B8NDg/BvFgrvWhoW6Fau/Rtcl/e+Nzur9K0NG93",
	"WlFq2X7Arm6cPi5e47KT/2trwn4VHVCAunIWyPX8kMeLpz2Tu+F0W5groMLfmNhbziwrd34KMZba3FRf",
	"1YJe8yQQQ/+Eo09XkNzsL2NauLOTTFDesTy4o2mGFy4ufx7D7MufO+zwVJCkIKOqNlZV3na9uH355Ov1",
	"Nr5v3S/5eu00p1hl1OdFhqRU0iWkgPfBWkGG/w9qhvGiBGfNYU1FPbuUZH92o+nhRRG3rnM5nyLLu14h",
	"urAI3l/2spSsIRpEcdmtVck1MeEyETlzJ2+VerGdj+yuxtb7VU/6e2Ig4y9Aoj+kxQf1SuK1q1wnzYW8",
	"X+yv8kNxB8tpMrWEKTSzAic6vGmQ5dVje739TwAAAP//cHcQefVIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
