//go:build go1.22

// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/nikpivkin/roasti-app-backend/internal/api/models"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for GetApiV1RecipesParamsListRecipesSortDirection.
const (
	Asc  GetApiV1RecipesParamsListRecipesSortDirection = "asc"
	Desc GetApiV1RecipesParamsListRecipesSortDirection = "desc"
)

// Valid indicates whether the value is a known member of the GetApiV1RecipesParamsListRecipesSortDirection enum.
func (e GetApiV1RecipesParamsListRecipesSortDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1RecipesParamsListRecipesSortField.
const (
	CreatedAt GetApiV1RecipesParamsListRecipesSortField = "created_at"
	Title     GetApiV1RecipesParamsListRecipesSortField = "title"
)

// Valid indicates whether the value is a known member of the GetApiV1RecipesParamsListRecipesSortField enum.
func (e GetApiV1RecipesParamsListRecipesSortField) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// CreateRecipeResponse Coffee brewing recipe
type CreateRecipeResponse = externalRef0.Recipe

// RecipePage defines model for RecipePage.
type RecipePage struct {
	Items      []externalRef0.Recipe       `json:"items"`
	Pagination externalRef0.PaginationMeta `json:"pagination"`
}

// UpdateRecipeResponse Coffee brewing recipe
type UpdateRecipeResponse = externalRef0.Recipe

// LimitParam defines model for LimitParam.
type LimitParam = int

// PageParam defines model for PageParam.
type PageParam = int

// GetApiV1RecipesParams defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParams struct {
	ListRecipes *externalRef0.ListRecipesParams `form:"listRecipes,omitempty" json:"listRecipes,omitempty"`
}

// GetApiV1RecipesParamsListRecipesSortDirection defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParamsListRecipesSortDirection string

// GetApiV1RecipesParamsListRecipesSortField defines parameters for GetApiV1Recipes.
type GetApiV1RecipesParamsListRecipesSortField string

// PostApiV1UploadsImagesMultipartBody defines parameters for PostApiV1UploadsImages.
type PostApiV1UploadsImagesMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PostApiV1AuthLoginJSONRequestBody defines body for PostApiV1AuthLogin for application/json ContentType.
type PostApiV1AuthLoginJSONRequestBody = externalRef0.LoginRequest

// PostApiV1AuthLogoutJSONRequestBody defines body for PostApiV1AuthLogout for application/json ContentType.
type PostApiV1AuthLogoutJSONRequestBody = externalRef0.LogoutRequest

// PostApiV1AuthRefreshJSONRequestBody defines body for PostApiV1AuthRefresh for application/json ContentType.
type PostApiV1AuthRefreshJSONRequestBody = externalRef0.RefreshRequest

// PostApiV1AuthRegisterJSONRequestBody defines body for PostApiV1AuthRegister for application/json ContentType.
type PostApiV1AuthRegisterJSONRequestBody = externalRef0.RegisterRequest

// PostApiV1RecipesJSONRequestBody defines body for PostApiV1Recipes for application/json ContentType.
type PostApiV1RecipesJSONRequestBody = externalRef0.CreateRecipeRequest

// PatchApiV1RecipesRecipeIdJSONRequestBody defines body for PatchApiV1RecipesRecipeId for application/json ContentType.
type PatchApiV1RecipesRecipeIdJSONRequestBody = externalRef0.PatchRecipeRequest

// PutApiV1RecipesRecipeIdJSONRequestBody defines body for PutApiV1RecipesRecipeId for application/json ContentType.
type PutApiV1RecipesRecipeIdJSONRequestBody = externalRef0.UpdateRecipeRequest

// PostApiV1UploadsImagesMultipartRequestBody defines body for PostApiV1UploadsImages for multipart/form-data ContentType.
type PostApiV1UploadsImagesMultipartRequestBody PostApiV1UploadsImagesMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with username and password
	// (POST /api/v1/auth/login)
	PostApiV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /api/v1/auth/logout)
	PostApiV1AuthLogout(w http.ResponseWriter, r *http.Request)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	PostApiV1AuthRefresh(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /api/v1/auth/register)
	PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request)
	// Get current user profile
	// (GET /api/v1/profiles/me)
	GetApiV1ProfilesMe(w http.ResponseWriter, r *http.Request)
	// List recipes
	// (GET /api/v1/recipes)
	GetApiV1Recipes(w http.ResponseWriter, r *http.Request, params GetApiV1RecipesParams)
	// Create recipe
	// (POST /api/v1/recipes)
	PostApiV1Recipes(w http.ResponseWriter, r *http.Request)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string)
	// Get recipe by ID
	// (GET /api/v1/recipes/{recipe_id})
	GetApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string)
	// Partially update recipe
	// (PATCH /api/v1/recipes/{recipe_id})
	PatchApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string)
	// Update recipe
	// (PUT /api/v1/recipes/{recipe_id})
	PutApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string)
	// Upload an image
	// (POST /api/v1/uploads/images)
	PostApiV1UploadsImages(w http.ResponseWriter, r *http.Request)
	// Get image by ID
	// (GET /api/v1/uploads/images/{image_id})
	GetApiV1UploadsImagesImageId(w http.ResponseWriter, r *http.Request, imageId string)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1ProfilesMe operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ProfilesMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1ProfilesMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Recipes operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Recipes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1RecipesParams

	// ------------- Optional query parameter "listRecipes" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "listRecipes", r.URL.Query(), &params.ListRecipes, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listRecipes", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Recipes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Recipes operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Recipes(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Recipes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1RecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1RecipesRecipeId(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1RecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1RecipesRecipeId(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiV1RecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiV1RecipesRecipeId(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiV1RecipesRecipeId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recipe_id" -------------
	var recipeId string

	err = runtime.BindStyledParameterWithOptions("simple", "recipe_id", r.PathValue("recipe_id"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipe_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiV1RecipesRecipeId(w, r, recipeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1UploadsImages operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1UploadsImages(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1UploadsImages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1UploadsImagesImageId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UploadsImagesImageId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "image_id" -------------
	var imageId string

	err = runtime.BindStyledParameterWithOptions("simple", "image_id", r.PathValue("image_id"), &imageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "image_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1UploadsImagesImageId(w, r, imageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/login", wrapper.PostApiV1AuthLogin)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/logout", wrapper.PostApiV1AuthLogout)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/refresh", wrapper.PostApiV1AuthRefresh)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/register", wrapper.PostApiV1AuthRegister)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/profiles/me", wrapper.GetApiV1ProfilesMe)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes", wrapper.GetApiV1Recipes)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/recipes", wrapper.PostApiV1Recipes)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.DeleteApiV1RecipesRecipeId)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.GetApiV1RecipesRecipeId)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.PatchApiV1RecipesRecipeId)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/recipes/{recipe_id}", wrapper.PutApiV1RecipesRecipeId)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/uploads/images", wrapper.PostApiV1UploadsImages)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/uploads/images/{image_id}", wrapper.GetApiV1UploadsImagesImageId)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}

type PostApiV1AuthLoginRequestObject struct {
	Body *PostApiV1AuthLoginJSONRequestBody
}

type PostApiV1AuthLoginResponseObject interface {
	VisitPostApiV1AuthLoginResponse(w http.ResponseWriter) error
}

type PostApiV1AuthLogin200JSONResponse externalRef0.AuthResponse

func (response PostApiV1AuthLogin200JSONResponse) VisitPostApiV1AuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthLogin400JSONResponse externalRef0.ApiErrorResponse

func (response PostApiV1AuthLogin400JSONResponse) VisitPostApiV1AuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthLogin401JSONResponse externalRef0.ApiErrorResponse

func (response PostApiV1AuthLogin401JSONResponse) VisitPostApiV1AuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthLogin500Response struct {
}

func (response PostApiV1AuthLogin500Response) VisitPostApiV1AuthLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostApiV1AuthLogoutRequestObject struct {
	Body *PostApiV1AuthLogoutJSONRequestBody
}

type PostApiV1AuthLogoutResponseObject interface {
	VisitPostApiV1AuthLogoutResponse(w http.ResponseWriter) error
}

type PostApiV1AuthLogout204Response struct {
}

func (response PostApiV1AuthLogout204Response) VisitPostApiV1AuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostApiV1AuthLogout400Response struct {
}

func (response PostApiV1AuthLogout400Response) VisitPostApiV1AuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostApiV1AuthLogout401Response struct {
}

func (response PostApiV1AuthLogout401Response) VisitPostApiV1AuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostApiV1AuthLogout500Response struct {
}

func (response PostApiV1AuthLogout500Response) VisitPostApiV1AuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostApiV1AuthRefreshRequestObject struct {
	Body *PostApiV1AuthRefreshJSONRequestBody
}

type PostApiV1AuthRefreshResponseObject interface {
	VisitPostApiV1AuthRefreshResponse(w http.ResponseWriter) error
}

type PostApiV1AuthRefresh200JSONResponse externalRef0.TokensResponse

func (response PostApiV1AuthRefresh200JSONResponse) VisitPostApiV1AuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthRefresh401JSONResponse externalRef0.ApiErrorResponse

func (response PostApiV1AuthRefresh401JSONResponse) VisitPostApiV1AuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthRefresh500Response struct {
}

func (response PostApiV1AuthRefresh500Response) VisitPostApiV1AuthRefreshResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostApiV1AuthRegisterRequestObject struct {
	Body *PostApiV1AuthRegisterJSONRequestBody
}

type PostApiV1AuthRegisterResponseObject interface {
	VisitPostApiV1AuthRegisterResponse(w http.ResponseWriter) error
}

type PostApiV1AuthRegister201JSONResponse externalRef0.AuthResponse

func (response PostApiV1AuthRegister201JSONResponse) VisitPostApiV1AuthRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthRegister400JSONResponse externalRef0.ApiErrorResponse

func (response PostApiV1AuthRegister400JSONResponse) VisitPostApiV1AuthRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthRegister409JSONResponse externalRef0.ApiErrorResponse

func (response PostApiV1AuthRegister409JSONResponse) VisitPostApiV1AuthRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthRegister422JSONResponse externalRef0.ApiErrorResponse

func (response PostApiV1AuthRegister422JSONResponse) VisitPostApiV1AuthRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthRegister500Response struct {
}

func (response PostApiV1AuthRegister500Response) VisitPostApiV1AuthRegisterResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetApiV1ProfilesMeRequestObject struct {
}

type GetApiV1ProfilesMeResponseObject interface {
	VisitGetApiV1ProfilesMeResponse(w http.ResponseWriter) error
}

type GetApiV1ProfilesMe200JSONResponse externalRef0.MyProfile

func (response GetApiV1ProfilesMe200JSONResponse) VisitGetApiV1ProfilesMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1ProfilesMe401Response struct {
}

func (response GetApiV1ProfilesMe401Response) VisitGetApiV1ProfilesMeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetApiV1RecipesRequestObject struct {
	Params GetApiV1RecipesParams
}

type GetApiV1RecipesResponseObject interface {
	VisitGetApiV1RecipesResponse(w http.ResponseWriter) error
}

type GetApiV1Recipes200JSONResponse RecipePage

func (response GetApiV1Recipes200JSONResponse) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Recipes400Response struct {
}

func (response GetApiV1Recipes400Response) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetApiV1Recipes500Response struct {
}

func (response GetApiV1Recipes500Response) VisitGetApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostApiV1RecipesRequestObject struct {
	Body *PostApiV1RecipesJSONRequestBody
}

type PostApiV1RecipesResponseObject interface {
	VisitPostApiV1RecipesResponse(w http.ResponseWriter) error
}

type PostApiV1Recipes201JSONResponse CreateRecipeResponse

func (response PostApiV1Recipes201JSONResponse) VisitPostApiV1RecipesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Recipes400Response struct {
}

func (response PostApiV1Recipes400Response) VisitPostApiV1RecipesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteApiV1RecipesRecipeIdRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type DeleteApiV1RecipesRecipeIdResponseObject interface {
	VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error
}

type DeleteApiV1RecipesRecipeId204Response struct {
}

func (response DeleteApiV1RecipesRecipeId204Response) VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1RecipesRecipeId400Response struct {
}

func (response DeleteApiV1RecipesRecipeId400Response) VisitDeleteApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetApiV1RecipesRecipeIdRequestObject struct {
	RecipeId string `json:"recipe_id"`
}

type GetApiV1RecipesRecipeIdResponseObject interface {
	VisitGetApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error
}

type GetApiV1RecipesRecipeId200JSONResponse externalRef0.Recipe

func (response GetApiV1RecipesRecipeId200JSONResponse) VisitGetApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1RecipesRecipeId403JSONResponse externalRef0.ApiErrorResponse

func (response GetApiV1RecipesRecipeId403JSONResponse) VisitGetApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1RecipesRecipeId404JSONResponse externalRef0.ApiErrorResponse

func (response GetApiV1RecipesRecipeId404JSONResponse) VisitGetApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1RecipesRecipeId500Response struct {
}

func (response GetApiV1RecipesRecipeId500Response) VisitGetApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PatchApiV1RecipesRecipeIdRequestObject struct {
	RecipeId string `json:"recipe_id"`
	Body     *PatchApiV1RecipesRecipeIdJSONRequestBody
}

type PatchApiV1RecipesRecipeIdResponseObject interface {
	VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error
}

type PatchApiV1RecipesRecipeId200JSONResponse externalRef0.Recipe

func (response PatchApiV1RecipesRecipeId200JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiV1RecipesRecipeId400JSONResponse externalRef0.ApiErrorResponse

func (response PatchApiV1RecipesRecipeId400JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiV1RecipesRecipeId403JSONResponse externalRef0.ApiErrorResponse

func (response PatchApiV1RecipesRecipeId403JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiV1RecipesRecipeId404JSONResponse externalRef0.ApiErrorResponse

func (response PatchApiV1RecipesRecipeId404JSONResponse) VisitPatchApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1RecipesRecipeIdRequestObject struct {
	RecipeId string `json:"recipe_id"`
	Body     *PutApiV1RecipesRecipeIdJSONRequestBody
}

type PutApiV1RecipesRecipeIdResponseObject interface {
	VisitPutApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error
}

type PutApiV1RecipesRecipeId200JSONResponse UpdateRecipeResponse

func (response PutApiV1RecipesRecipeId200JSONResponse) VisitPutApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1RecipesRecipeId400JSONResponse externalRef0.ApiErrorResponse

func (response PutApiV1RecipesRecipeId400JSONResponse) VisitPutApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1RecipesRecipeId403JSONResponse externalRef0.ApiErrorResponse

func (response PutApiV1RecipesRecipeId403JSONResponse) VisitPutApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1RecipesRecipeId404JSONResponse externalRef0.ApiErrorResponse

func (response PutApiV1RecipesRecipeId404JSONResponse) VisitPutApiV1RecipesRecipeIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1UploadsImagesRequestObject struct {
	Body *multipart.Reader
}

type PostApiV1UploadsImagesResponseObject interface {
	VisitPostApiV1UploadsImagesResponse(w http.ResponseWriter) error
}

type PostApiV1UploadsImages201JSONResponse externalRef0.Image

func (response PostApiV1UploadsImages201JSONResponse) VisitPostApiV1UploadsImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1UploadsImages400Response struct {
}

func (response PostApiV1UploadsImages400Response) VisitPostApiV1UploadsImagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostApiV1UploadsImages413Response struct {
}

func (response PostApiV1UploadsImages413Response) VisitPostApiV1UploadsImagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(413)
	return nil
}

type PostApiV1UploadsImages500Response struct {
}

func (response PostApiV1UploadsImages500Response) VisitPostApiV1UploadsImagesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetApiV1UploadsImagesImageIdRequestObject struct {
	ImageId string `json:"image_id"`
}

type GetApiV1UploadsImagesImageIdResponseObject interface {
	VisitGetApiV1UploadsImagesImageIdResponse(w http.ResponseWriter) error
}

type GetApiV1UploadsImagesImageId200ImageResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response GetApiV1UploadsImagesImageId200ImageResponse) VisitGetApiV1UploadsImagesImageIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetApiV1UploadsImagesImageId404Response struct {
}

func (response GetApiV1UploadsImagesImageId404Response) VisitGetApiV1UploadsImagesImageIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetApiV1UploadsImagesImageId500Response struct {
}

func (response GetApiV1UploadsImagesImageId500Response) VisitGetApiV1UploadsImagesImageIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login with username and password
	// (POST /api/v1/auth/login)
	PostApiV1AuthLogin(ctx context.Context, request PostApiV1AuthLoginRequestObject) (PostApiV1AuthLoginResponseObject, error)
	// Logout user
	// (POST /api/v1/auth/logout)
	PostApiV1AuthLogout(ctx context.Context, request PostApiV1AuthLogoutRequestObject) (PostApiV1AuthLogoutResponseObject, error)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	PostApiV1AuthRefresh(ctx context.Context, request PostApiV1AuthRefreshRequestObject) (PostApiV1AuthRefreshResponseObject, error)
	// Register a new user
	// (POST /api/v1/auth/register)
	PostApiV1AuthRegister(ctx context.Context, request PostApiV1AuthRegisterRequestObject) (PostApiV1AuthRegisterResponseObject, error)
	// Get current user profile
	// (GET /api/v1/profiles/me)
	GetApiV1ProfilesMe(ctx context.Context, request GetApiV1ProfilesMeRequestObject) (GetApiV1ProfilesMeResponseObject, error)
	// List recipes
	// (GET /api/v1/recipes)
	GetApiV1Recipes(ctx context.Context, request GetApiV1RecipesRequestObject) (GetApiV1RecipesResponseObject, error)
	// Create recipe
	// (POST /api/v1/recipes)
	PostApiV1Recipes(ctx context.Context, request PostApiV1RecipesRequestObject) (PostApiV1RecipesResponseObject, error)
	// Delete recipe
	// (DELETE /api/v1/recipes/{recipe_id})
	DeleteApiV1RecipesRecipeId(ctx context.Context, request DeleteApiV1RecipesRecipeIdRequestObject) (DeleteApiV1RecipesRecipeIdResponseObject, error)
	// Get recipe by ID
	// (GET /api/v1/recipes/{recipe_id})
	GetApiV1RecipesRecipeId(ctx context.Context, request GetApiV1RecipesRecipeIdRequestObject) (GetApiV1RecipesRecipeIdResponseObject, error)
	// Partially update recipe
	// (PATCH /api/v1/recipes/{recipe_id})
	PatchApiV1RecipesRecipeId(ctx context.Context, request PatchApiV1RecipesRecipeIdRequestObject) (PatchApiV1RecipesRecipeIdResponseObject, error)
	// Update recipe
	// (PUT /api/v1/recipes/{recipe_id})
	PutApiV1RecipesRecipeId(ctx context.Context, request PutApiV1RecipesRecipeIdRequestObject) (PutApiV1RecipesRecipeIdResponseObject, error)
	// Upload an image
	// (POST /api/v1/uploads/images)
	PostApiV1UploadsImages(ctx context.Context, request PostApiV1UploadsImagesRequestObject) (PostApiV1UploadsImagesResponseObject, error)
	// Get image by ID
	// (GET /api/v1/uploads/images/{image_id})
	GetApiV1UploadsImagesImageId(ctx context.Context, request GetApiV1UploadsImagesImageIdRequestObject) (GetApiV1UploadsImagesImageIdResponseObject, error)

	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostApiV1AuthLogin operation middleware
func (sh *strictHandler) PostApiV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1AuthLoginRequestObject

	var body PostApiV1AuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1AuthLogin(ctx, request.(PostApiV1AuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1AuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1AuthLoginResponseObject); ok {
		if err := validResponse.VisitPostApiV1AuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1AuthLogout operation middleware
func (sh *strictHandler) PostApiV1AuthLogout(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1AuthLogoutRequestObject

	var body PostApiV1AuthLogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1AuthLogout(ctx, request.(PostApiV1AuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1AuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1AuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostApiV1AuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1AuthRefresh operation middleware
func (sh *strictHandler) PostApiV1AuthRefresh(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1AuthRefreshRequestObject

	var body PostApiV1AuthRefreshJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1AuthRefresh(ctx, request.(PostApiV1AuthRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1AuthRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1AuthRefreshResponseObject); ok {
		if err := validResponse.VisitPostApiV1AuthRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1AuthRegister operation middleware
func (sh *strictHandler) PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1AuthRegisterRequestObject

	var body PostApiV1AuthRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1AuthRegister(ctx, request.(PostApiV1AuthRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1AuthRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1AuthRegisterResponseObject); ok {
		if err := validResponse.VisitPostApiV1AuthRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1ProfilesMe operation middleware
func (sh *strictHandler) GetApiV1ProfilesMe(w http.ResponseWriter, r *http.Request) {
	var request GetApiV1ProfilesMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1ProfilesMe(ctx, request.(GetApiV1ProfilesMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1ProfilesMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1ProfilesMeResponseObject); ok {
		if err := validResponse.VisitGetApiV1ProfilesMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1Recipes operation middleware
func (sh *strictHandler) GetApiV1Recipes(w http.ResponseWriter, r *http.Request, params GetApiV1RecipesParams) {
	var request GetApiV1RecipesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Recipes(ctx, request.(GetApiV1RecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Recipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1RecipesResponseObject); ok {
		if err := validResponse.VisitGetApiV1RecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Recipes operation middleware
func (sh *strictHandler) PostApiV1Recipes(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1RecipesRequestObject

	var body PostApiV1RecipesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Recipes(ctx, request.(PostApiV1RecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Recipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1RecipesResponseObject); ok {
		if err := validResponse.VisitPostApiV1RecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1RecipesRecipeId operation middleware
func (sh *strictHandler) DeleteApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request DeleteApiV1RecipesRecipeIdRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1RecipesRecipeId(ctx, request.(DeleteApiV1RecipesRecipeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1RecipesRecipeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApiV1RecipesRecipeIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1RecipesRecipeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1RecipesRecipeId operation middleware
func (sh *strictHandler) GetApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request GetApiV1RecipesRecipeIdRequestObject

	request.RecipeId = recipeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1RecipesRecipeId(ctx, request.(GetApiV1RecipesRecipeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1RecipesRecipeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1RecipesRecipeIdResponseObject); ok {
		if err := validResponse.VisitGetApiV1RecipesRecipeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchApiV1RecipesRecipeId operation middleware
func (sh *strictHandler) PatchApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request PatchApiV1RecipesRecipeIdRequestObject

	request.RecipeId = recipeId

	var body PatchApiV1RecipesRecipeIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchApiV1RecipesRecipeId(ctx, request.(PatchApiV1RecipesRecipeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchApiV1RecipesRecipeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchApiV1RecipesRecipeIdResponseObject); ok {
		if err := validResponse.VisitPatchApiV1RecipesRecipeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiV1RecipesRecipeId operation middleware
func (sh *strictHandler) PutApiV1RecipesRecipeId(w http.ResponseWriter, r *http.Request, recipeId string) {
	var request PutApiV1RecipesRecipeIdRequestObject

	request.RecipeId = recipeId

	var body PutApiV1RecipesRecipeIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiV1RecipesRecipeId(ctx, request.(PutApiV1RecipesRecipeIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiV1RecipesRecipeId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutApiV1RecipesRecipeIdResponseObject); ok {
		if err := validResponse.VisitPutApiV1RecipesRecipeIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1UploadsImages operation middleware
func (sh *strictHandler) PostApiV1UploadsImages(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1UploadsImagesRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1UploadsImages(ctx, request.(PostApiV1UploadsImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1UploadsImages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1UploadsImagesResponseObject); ok {
		if err := validResponse.VisitPostApiV1UploadsImagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1UploadsImagesImageId operation middleware
func (sh *strictHandler) GetApiV1UploadsImagesImageId(w http.ResponseWriter, r *http.Request, imageId string) {
	var request GetApiV1UploadsImagesImageIdRequestObject

	request.ImageId = imageId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1UploadsImagesImageId(ctx, request.(GetApiV1UploadsImagesImageIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1UploadsImagesImageId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1UploadsImagesImageIdResponseObject); ok {
		if err := validResponse.VisitGetApiV1UploadsImagesImageIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW3PbuPX/Khj8/w9th7HkJM20estlu+tZZ+PJbrYPGY8GIo5EbECAAUDbakbfvQOA",
	"d4IUo1hrN6OXxCaBg4PfueIc0F9wLNNMChBG48UXnBFFUjCg3G+XLGXmyj6yv1HQsWKZYVLgBX5L7lia",
	"p0jk6QoUkmukIGYZaGQkUmByJXCEmR36OQe1xREWJAW8wNxSxRHWcQIp8ZTXJOcGL57OI2y2mR3FhIEN",
	"KLzbRfiKbGCADfuqsfjAkhnZQHjF8+CCqaTA9fKSafPeE3bLO1DgLuOSAl4YlcPQDqt5rVUJ5+/WePHx",
	"C/5/BWu8wP83q+Gf+XF6Vix+RTZMELvNYu1d9AVnSmagDAPHCslNItUF7cPyL8YNKLTaIj8GV9vURjGx",
	"wbsIrxTcvgWTSDd/Akev6gm7CFO2XrM452Y7cfqbesIuwloqs6RMQexZ7u7gV6kMqt9HGESe4sVHTHSM",
	"IzcYXwd25eiuGfAgKsCp1U87CK22EYKzzRmKFRADdElMhAwzHCLU2Fy9cj3OwmkHBjjYVU/k6g+IDd5d",
	"W67Mlttna6lSN6bAxvL42pH1+vIedCaFhj7vr+V6DYCs0JjYFPqOo6BGLFlg8xdvrJ2YBFCuQaHbRJYb",
	"dw8rgn09ASL0MEP2rSVJ0VqqNimRc05WvLKVoAou08N1sCGRHn+/sRS0IWmGbhMQDcbQLdHl1nHkRGLn",
	"Y0oMPDEsDYLQot1d6g0YwjhQ1Hhcgj2M6zcaUEjGHwT7nFf7ZBSEYWsGQfNnKdnAPk3JuCQUKHKDz9Br",
	"ItDK0teS3wBFN4y4ce51MRqBoJlkwpxN0YAsX3EWB3gQlMXEgLbSMwk0NQsxjfw8vkU3TLMVh7N6iysp",
	"ORBhqStJtFlyuAE+EeP3dsalm+DMFrKA6r9TFBRQZP28hao0Sj88wsyAjxUTFfpXAxmuHQdRijgRex/T",
	"W967Cu+qQpLNM3qgVXCiDSqmTzQNizJ8zpkCan0ks/NqL1TuoW1AbcNvWUKJeaUZUdvtNvZ23fO0UQGN",
	"TQoOibcQiLGVLL9GqJ6NvkjDweGD29MpAJwCwCkAnALAKQB8SwAoQH2ZsR+UkqrpTtuOEuzrPjw/5SkR",
	"TxQQarUWuVEoBa39CXJ8757mGFu5SYZZInEMWi+N/AShA1EilXnCmTU7N8S5W4u0NfKYGB8VPuegjQ5p",
	"hYK1Ap0M0f/N0XR+3EgkV4YwgQgScIs8Y37VoL5pUBO1/YOGWihd/NocRm1AimVG0H3VOtCORs9K88qz",
	"3c2LudV3BSJOlpkCbSEkoGT5s90G3NkfJKdLS8fOvnOv5TIlccKE1ZBUfiLLTJrg4bRr8n0hM7Hh4PxI",
	"6YJLljMlY89KW2umBSYmtFG5O0vrKk7bZYKBKVeu8LDUEEtBQw7Q/UA4KoeW3DrOmUDlzMEIUJVbRgOZ",
	"J9cMY5VLYsK8eI6D9B5FYJM2RgyEji5aoTyhsaGBMOA8go8CTYLTXLRnr1/HCFqVVdYrsrUgOEdFKfPy",
	"v2qo4ppwDdFJoU8KuE8BJ+vem1aG3NGE6h1y+V0v3y5dOxBt04oUKMtTHOGEKDrmnS/S4vjY8UgtgfW0",
	"dsSJeRGOJeN9Ax0B5VJumHjvA/1ea2wzmRGtb6UKsWqPhNXrhpttPEuZuASxMUmzbN7OAnwBfACHasAe",
	"Uh00GhxUFMbhkblp4NOGoJcFjS/eHj6y7NvtlZJrxr++8NBOia5rkldBPfwRBCgWo8z3B4Ban+EnR0O1",
	"izaFy+LU4l4jaa3fHqi8VpdzAqeRrOpITEz26hbGWzCkr+ZuqRbdEYA7xHqCjXOlQJhlFkTttX/rdln0",
	"rDrJxLOnXi9Zat3GedCvW4aXscxF4GD1S9UIa+AKKG4sPLriPLSiPY8N7OjSHtW+aTsC7oaI/wJ330Q8",
	"JOkCuKgtqSYbzf1O0oS6K9fWBd9i7HYWx+WVOQc4ICTf7MSL8/l8H6o1oHWLMdCzPBjXYVRMnJRFxEOC",
	"Q1XmO3rVrpPh3XthrJF+HVx/+ndVdWJ6pOx0lKpTlW7t7S1W0i8qzqeq8alqfKoan6rGp6rxIVXjsns4",
	"rdAxED0fn7t7hE7o0TmRIlcL1rC+1qn8r/uU0gDuy7V0bP1A0x61W3dIPyzt3dMWKWgXLRffFrHWktu9",
	"IS43TCCpkIIN08aXDvciMLmo8N5RBXXYzsgNMURNNTM/+njWtmJyqILoMssVkxtFsmQ7hRikhPGBKpZ7",
	"hwilReemCkd+UsgRTCuLnaG3uTYWln88efYUxQlRJDag9NlAwezwElm91Isn5y8aS0WIg/E/+BOkRkRQ",
	"lAsKSsdSgUZS8O3Z/l5lAcZXVtcaTmko1jlP52uyjSosZ5vEVGXYZfvX+jkl6pO1f/vfSI3WNSv1d9dK",
	"7cio0/+c7DZaFcU+Nt+vWxg53Dhi40ebrylgT0hnR8zJxnOIc8XM9lfXWHaCeQVEgXqZm8T+5oKzSyLc",
	"43rNxJgM7ywNJtYOvCIqY2ecDL3MMhzhG1Dacz8/m5+du45QBoJkDC/ws7P52dxZv0nc2jOSsdnN+cwa",
	"wcxFNac40gcdqz4utF1QvMBXUpuXGfv93LLquhHYbx+0eSWpSwljKQz4MinJMu6MSorZH9rnoPWd+Al5",
	"SavhsWtjbRXBPfDa7vbydD6/bxZaFzccC51irMsDdO4Mdp27jO35EdjoXmsJsPKK0NJ3eS7OH4KLC3FD",
	"OKMoVuBsjnBtufm7x6Q71lhL4UiDurEB3F2jaRoJXny8jrDO05SobQX3LTNJZZMuDDZjL9lo50OtOVW5",
	"/rWl2tV1mZvpym4HH1vbG/2rSer+PNAdkJsNUCRz09BKvm3o5RSt6XpBf0Jn/wF6iDCb4rOMufs8HUn1",
	"BVREvYkSKtL144qoc954GJfUSYECNujTkAI/oAFFeFDXIBWCu8xiVvJYpEX35yfKw1s365roG1Rx/Jqs",
	"e8XwIytf+0w4SfvO/+yA6A5OJX5B3XscwfGfD8HFhzJmyeq0yhUQukWGFAbw/OnTh+Dsd2uZ/v5TYV33",
	"aIteGYqDUMj5h00x8/cq9Mxn5hsI2OGP4M2wuIOh3wI+vgeur3wEkCwvHLhzR1aOmxRZW7HyRzDVHYIW",
	"rRq7EqA2bOUXsfsgqz9UbX78O3B1pR4yG/xGdnd9ROgbH/gEQL+q7sSU9dAShYl5z+EpjV2v/gi5FE35",
	"5HoX7YsgtRyOGjyaHY4/OXQEP3QNSLGoJpe91kmiawnDL9RoX/Sk0beT2Rf/w5LRnV+Lg4G+vN64502J",
	"+f8uaN+C3Lfh9ohdfxpeLYK7yDc/FO9WF66npPyes0Pw8jPH8Iom+ZAHQWJ+HBsZVkwP8LOHCM+/SIMI",
	"5/IWKPqLsL+4sPFXz9Lzh2CpMFbLzFrm4tsOhjbYFX211RZdvBnypMTEScCV2scPoY9Hc9eBO10Pc9jc",
	"ZxNV9/8RpfYnCx2y0JbNXRFlGOF8W8hwPAxkeSiHyc13ZXYHZEn3p/LBr8FPhvf9Gd6HvebWyFJ9a03P",
	"XKNNTyhI+c9V9IUfP2Yuac4Ny4gys7VU6RNK/O36Go52+7D8xqFqeK+YIO6vH433xNy8QCvsIapX/hOf",
	"UG2y0cccrlqN6//5s+DfYwJkpEScKPdnJg7PkbxgERHVh0il4hQ6MqY4sy/l1avd3sJAS4PcvxNdenW7",
	"634Te0d29re2sPdr4YCM63pM4Cjlh9xfTuvb492Uti2vBAj3nd8hqfzkR+wFysCdmWWcsI5hwB1JM9co",
	"fvfzFKDe/Wyfdmp67Tb1x2sruGJDk+6ea5QSQTaQgvsWpJUF+L9xNmyRrsenwCgGN4TXs0sg+7MbZWiP",
	"ZdS65iGFI+nvgIT4cmXJPtl3pWg0UsD9ZXjZKs/pCDER85zanbfqd65P6cqc1djGH6orn/TX/KG4VaGR",
	"SYhBVDr9LAyss6sGQV9Q3V3v/hsAAP//RVkSoOtPAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
