# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/_archive_/schemas/v3.0/schema.yaml
openapi: 3.0.0
info:
  title: Models only
  version: 0.0.1
components:

  parameters:
    ListRecipesParams:
      name: listRecipes
      in: query
      style: form
      explode: true
      schema:
        allOf:
          - $ref: '#/components/schemas/Pagination'
          - type: object
            properties:
              authorId:
                type: string
                description: Filter by author
              brewMethod:
                $ref: '#/components/schemas/BrewMethod'
              difficulty:
                $ref: '#/components/schemas/Difficulty'

  schemas:
    Pagination:
      type: object
      properties:
        limit:
          type: integer
          default: 20
        page:
          type: integer
          default: 1

    BrewMethod:
      type: string
      description: Coffee brewing method
      enum:
        - none
        - v60
        - french_press
        - aeropress
        - chemex
        - cold_brew
        - expresso_machine
        - moka_pot

    Difficulty:
      type: string
      description: Difficulty level of the recipe
      enum:
        - none
        - easy
        - medium
        - hard

    RoastLevel:
      type: string
      nullable: true
      description: Coffee roast level
      default: none
      enum:
        - none
        - ligth
        - medium_light
        - medium
        - medium_dark
        - dark

    BrewStep:
      type: object
      description: Single step of the brewing process
      properties:
        order:
          type: integer
          description: Order of the step in the recipe
        title:
          type: string
          description: Short title of the step
        description:
          type: string
          description: Detailed instructions for the step
        duration_seconds:
          type: integer
          nullable: true
          description: Optional duration of the step in seconds
      required:
        - order
        - title
        - description

    Recipe:
      type: object
      description: Coffee brewing recipe
      properties:
        id:
          type: string
          description: Unique recipe identifier
        author_id:
          type: string
          description: ID of the user who created the recipe
        title:
          type: string
          description: Recipe title
        description:
          type: string
          description: Detailed description of the recipe
        image_url:
          type: string
          nullable: true
          description: Optional image illustrating the recipe
        brew_method:
          $ref: '#/components/schemas/BrewMethod'
        difficulty:
          $ref: '#/components/schemas/Difficulty'
        roast_level:
          $ref: '#/components/schemas/RoastLevel'
        beans:
          type: string
          nullable: true
          description: Coffee beans used for the recipe
        public:
          type: boolean
          description: Indicates whether the recipe is publicly visible.
        created_at:
          type: string
          format: date-time
          description: "Timestamp when the recipe was created"

        updated_at:
          type: string
          format: date-time
          description: "Timestamp when the recipe was last updated"
        steps:
          type: array
          description: Ordered list of brewing steps
          items:
            $ref: '#/components/schemas/BrewStep'
      required:
        - id
        - author_id
        - title
        - description
        - brew_method
        - difficulty
        - steps
        - public

    CreateRecipeRequest:
      type: object
      additionalProperties: false
      required:
        - title
        - description
        - brew_method
        - difficulty
        - steps
      properties:
        title:
          type: string
        description:
          type: string
        image_url:
          type: string
          nullable: true
          description: Optional image illustrating the recipe
        brew_method:
          $ref: '#/components/schemas/BrewMethod'
        difficulty:
          $ref: '#/components/schemas/Difficulty'
        roast_level:
          $ref: '#/components/schemas/RoastLevel'
        beans:
          type: string
        public:
          type: boolean
          default: false
          description: Whether this recipe is publicly visible
        steps:
          type: array
          items:
            $ref: '#/components/schemas/BrewStep'

    PatchRecipeRequest:
        type: object
        properties:
          title:
            type: string
          description:
            type: string
          image_url:
            type: string
            nullable: true
          brew_method:
            $ref: '#/components/schemas/BrewMethod'
          difficulty:
            $ref: '#/components/schemas/Difficulty'
          roast_level:
            $ref: '#/components/schemas/RoastLevel'
          beans:
            type: string
            nullable: true
          public:
            type: boolean
            description: Whether this recipe is publicly visible
        additionalProperties: false

    ApiErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Human-readable error message
      required:
        - error