# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/_archive_/schemas/v3.0/schema.yaml
openapi: 3.0.0
info:
  version: 0.0.1
  title: Roasti App
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  /api/v1/recipes:
    get:
      summary: List recipes
      parameters:
        - $ref: '#/components/parameters/UserIDHeader'
        - $ref: './models.yaml#/components/parameters/ListRecipesParams'
      responses:
        '200':
          description: Paginated list of recipes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipePage'
        '400':
          description: Bad request
        '500':
          description: Internal server error

    post:
      summary: Create recipe
      parameters:
        - $ref: '#/components/parameters/UserIDHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models.yaml#/components/schemas/CreateRecipeRequest'
      responses:
        '201':
          description: Recipe created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRecipeResponse'
        '400':
          description: Bad request

  /api/v1/recipes/{recipe_id}:
    delete:
      summary: Delete recipe
      parameters:
        - $ref: '#/components/parameters/UserIDHeader'
        - in: path
          name: recipe_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
        '400':
          description: Bad request

    patch:
      summary: Update recipe
      parameters:
        - $ref: '#/components/parameters/UserIDHeader'
        - name: recipe_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models.yaml#/components/schemas/PatchRecipeRequest'
      responses:
        '200':
          description: Recipe updated
          content:
            application/json:
              schema:
                $ref: './models.yaml#/components/schemas/Recipe'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './models.yaml#/components/schemas/ApiErrorResponse'
        '403':
          description: Not allowed (not author)
          content:
            application/json:
              schema:
                $ref: './models.yaml#/components/schemas/ApiErrorResponse'
        '404':
          description: Recipe not found
          content:
            application/json:
              schema:
                $ref: './models.yaml#/components/schemas/ApiErrorResponse'

components:
  parameters:
    UserIDHeader:
      name: X-User-Id
      in: header
      description: User ID
      schema:
        type: string
        default: test-user
      required: true

    LimitParam:
      name: limit
      in: query
      description: Maximum number of recipes to return
      required: false
      schema:
        type: integer
        default: 20

    PageParam:
      name: page
      in: query
      description: Page of recipes
      required: false
      schema:
        type: integer
        default: 1

  schemas:
    Page:
      type: object
      description: Generic paginated response
      properties:
        items:
          type: array
          items: {}
          description: List of items on this page
        page:
          type: integer
          format: int
          description: Current page number
        limit:
          type: integer
          format: int
          description: Maximum number of items per page
        total_count:
          type: integer
          format: int
          description: Total number of items available
      required:
        - items
        - page
        - limit
        - total_count
    RecipePage:
      allOf:
        - $ref: '#/components/schemas/Page'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: './models.yaml#/components/schemas/Recipe'

    CreateRecipeResponse:
      $ref: './models.yaml#/components/schemas/Recipe'

